### ISSUE TITLE
add support for list *and* watching from a single method call

### ISSUE THREAD

**Issue by jtnord** [fabric8io/kubernetes-client#1014]
Kubernetes supports a list resource and watch for changes, however the kubernetes-client does not expose this.

Currently you have to watch the resource and perform a list and then reconcile differences, which has timing issues and causes client code to be more complicated than it needs to be.

in other words I would like to be able to do the equivalent of the following in Java: 

```
kubectl get secrets -l example.com/foo --watch --watch-only=false
```

but I am only able to do the equivalent of:

```
kubectl get secrets -l example.com/foo --watch --watch-only=true
kubectl get secrets -l example.com/foo
```

**Comment by jtnord** [comment]
what would make it slightly easier to work around would be the ability to watch the `resourceList` after a given resource version as documented [here](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#concurrency-control-and-consistency), but for some undocumented reason this was [deprecated](https://github.com/fabric8io/kubernetes-client/commit/6e89a5a85aafccb305f51da29b8c7746189947c7).

**Comment by ljnelson** [comment]
It would be nice to have this in the project for sure.  I ended up implementing it in part in my [fledgling controller framework](https://github.com/microbean/microbean-kubernetes-controller) based on the fabric8 Kubernetes client and aping the `tools/cache` package from Kubernetes' `client-go` and, while tracing the code, could find no obvious reason for the deprecation you mention.  You have to, in fact, make use of it to implement reflectors properly, as my understanding is the presence of a resource version (even of `0`) during a list operation is necessary to instruct Kubernetes to serve results from its own cache instead of going straight to `etcd`.

(In case it's helpful, I also [documented my journey](https://lairdnelson.wordpress.com/2018/01/07/understanding-kubernetes-tools-cache-package-part-0/) in this area.)

**Comment by jtnord** [comment]
as far as I have been able to uncover without documentation the API call of
`.watch(version, theWatcher)` should be `.withResourceVersion(version).watch(theWatcher)`
