### ISSUE TITLE
OpenShift 3.5 and apiVersions

### ISSUE THREAD

**Issue by ghost** [fabric8io/kubernetes-client#1017]
Hi,

Eclipse Che uses fabtic8 client to create workspace objects. Everything works fine with 3.6+ versions. However, a user with 3.5 has hit the below issue:

https://github.com/eclipse/che/issues/8847

Can an engineer comment on it please?

**Comment by piyush1594** [comment]
Hey @eivantsov,

The latest version of Kubernetes-client is not by default compatible with OpenShift 1.5 and below. There is this thing which you can do to make it work with previous OpenShift versions.

```
You can also set the apiVersion of the resource like in the case of SecurityContextConstraints :

SecuirtyContextConstraints scc = new SecurityContextConstraintsBuilder()
		.withApiVersion("v1")
		.withNewMetadata().withName("scc").endMetadata()
		.withAllowPrivilegedContainer(true)
		.withNewRunAsUser()
		.withType("RunAsAny")
		.endRunAsUser()
		.build();
```

So in case of a route you just need to do this addition.

```
.withApiVersion("v1")
```

This should ideally work. Let us know if this does not resolve your problem. This is because of the changes in ApiVersion Group from Openshift 3.6 onwards.

Thanks
