### ISSUE TITLE
something drops '-' from Singular/Plural forms of CustomResources.

### ISSUE THREAD

**Issue by ensonic** [fabric8io/kubernetes-client#1109]
I define a CustomResource like this:
```java
public static final CustomResourceDefinition DEFINITION =
    new CustomResourceDefinitionBuilder()
        .withNewMetadata()
        .withName("foo-bar.baz.example.com")
        .endMetadata()
        .withNewSpec()
        .withGroup("baz.example.com")
        .withVersion("v1alpha1")
        .withScope("Namespaced")
        .withNewNames()
        .withKind("FooBar")
        .withPlural("foo-bars")
        .withSingular("foo-bar")
        .endNames()
        .endSpec()
        .build();
```
Now a simple test fails:
```java
FooBar fb1 = new FooBar();
fb1.getMetadata().setName("example");
FooBar.client(client).inNamespace("default").create(fb1);

FooBar fb2 = FooBar.client(client).inNamespace("default").withName("example").get();
```
and this fails with a 404. I added some more printf
https://github.com/ensonic/kubernetes-client/commit/29d8096a25b961cd88cfeb9b7aafa0476560107d
and what I see is this:
```
Query string: '/apis/baz.example.com/v1alpha1/namespaces/default/foo-bars/example'
Query attributes: '{attributes: {namespace={key:namespace, value:default}, name={key:name, value:example}, kind={key:kind, value:foo-bar}}}'
Comparing attributes: '{attributes: {namespace={key:namespace, value:default}, name={key:name, value:example}, kind={key:kind, value:foobar}}}'
```

So, something elmininated the '-' in the kind, when the object was created. When I do this with kubernetes itself it works though. Also 
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
suggests that dashes are allowed. I am a bit lost at finding the code that is responsible for it.

**Comment by ensonic** [comment]
Ping?

**Comment by rohanKanojia** [comment]
@ensonic : Hi, Try looking  in [KubernetesAttributesExtractor](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java). It would be nice if you could raise a PR for this :)

**Comment by rohanKanojia** [comment]
@ensonic : Does it make any difference to your test?

**Comment by rohanKanojia** [comment]
@ensonic : Could you please provide a test case if you have time so that someone who wants to work on this can get help from that?

**Comment by ensonic** [comment]
I don't have a sample anymore since we dropped dashes to work around it. The first post has all the infos.

**Comment by sbaier1** [comment]
This is still the case, and makes it basically impossible to write tests in CRUD mode when using CRDs.

As far as i can tell from some debugging, the dash is "lost" in AttributeSet#merge, where the kind is being overwritten due to two AttributeSets being passed into it in CrudDispatcher#handleCreate where the second argument being the AttributeSet extracted from the resource, which does not contain a dash, thus overwriting the kind from the first argument.

Not sure if i have the time to fix it but maybe this is of help to a contributor here.

**Comment by manusa** [comment]
relates to: #2049

**Comment by manusa** [comment]
## Analysis
The problem is not in the plural, but with the name not being resolved into an attribute key.
The following test demonstrates the problem: https://github.com/manusa/kubernetes-client/blob/83278ad8980ddda0ea873710f426943dbef40575/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest1109.java#L47

Basically when performing the API get, the attributes are resolved correctly, but the existing Map doesn't match for all the attributes (see screenshots):

query AttributeSet atrributes Map contains 3 entries (one of them being `name: example`):
![image](https://user-images.githubusercontent.com/488391/77751018-31cf6e00-7025-11ea-84c3-1665237ba775.png)

The matching map entry key contains only 2 attributes instead (missing `name: example`):
![image](https://user-images.githubusercontent.com/488391/77751237-95f23200-7025-11ea-816b-c89c331e5a13.png)

So the line
https://github.com/fabric8io/kubernetes-client/blob/8321522e75d0e6f5b5ef0aadea3d82f07beff758/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java#L58

fails to match with any of the entries.

In order to fix this, the matches clause should be replaced for something less restrictive (probably just reversing it to `query.matches(entry.getKey())`.
