### ISSUE TITLE
Question about concurrency on edit/patch deployments

### ISSUE THREAD

**Issue by podviaznikov** [fabric8io/kubernetes-client#1153]
Reading through the code I see that `.edit` and `.patch` function on `Deployment` behave in the following way:

1. create new `updated` version of `Deployment` - up to the user of the library
2. the library will fetch the `current` version
3. the library will calculate JSON operation diff inside `handlePatch` function and send k8s patch `request`.

I see the problem with step 2 if there are 2 processes updating the same deployment.
Lets say 1st process updates `spec.replicas` and 2nd updates `annotations`.
If process 2 completed step 2. Process 1 updated number of replicas then process 1 will reset number of replicas to the old value (because in memory object is already outdated).

Question:
 - did I correctly describe potential scenario?
 - if scenario is possible because library relies on read-write sequence, is there lower level function expose that will not calculate diffs but will allow user of the library to specify diff?

**Comment by jglick** [comment]
> process 1 will reset number of replicas to the old value

I guess you mean process 1 will reset the annotations to the old value, reverting the change made by process 2. If so, I have experienced this problem by running a test that includes two concurrent processes dealing with a CR and using patch operations where possible. (Both happen to be inside one JVM; one is a modification of [this code](https://github.com/jenkinsci/jx-resources-plugin/blob/338f69342f867ed4f4b70e3abd9d3edcc99700c5/src/main/java/org/jenkinsci/plugins/jx/resources/BuildSyncRunListener.java#L329).) After setting a breakpoint in `OperationSupport`:

```java
  protected <T> T handlePatch(T current, T updated, Class<T> type) throws ExecutionException, InterruptedException, KubernetesClientException, IOException {
    JsonNode diff = JsonDiff.asJson(patchMapper().valueToTree(current), patchMapper().valueToTree(updated));
    RequestBody body = RequestBody.create(JSON_PATCH, JSON_MAPPER.writeValueAsString(diff)); // ← HERE
```

In NetBeans, you can configure this breakpoint to continue rather than suspend and to print text

```
Patching: {=diff.toString()}
```

Sometimes when I run this, I see a series of changes along these lines:

```json
[{"op":"add","path":"/spec/stuff","value":[{"data":[{"name":"x","val":1},{"name":"y","val":2}]}]}]
[{"op":"replace","path":"/spec/stuff/0/data/0/val","value":3},{"op":"replace","path":"/spec/stuff/0/data/1/val","value":4}]
[{"op":"replace","path":"/spec/unrelated","value":"something"},{"op":"replace","path":"/spec/stuff/0/data/1/val","value":1},{"op":"replace","path":"/spec/stuff/0/data/1/val","value":2}]
```

One process added something to `.spec.stuff` and later amended it. Another process is supposed to editing `.spec.unrelated` but it winds up reverting the changes to `.spec.stuff`.

I think there is only one way to fix this: deprecate the existing `patch` methods as fundamentally flawed, and introduce new overloads that take an explicit `T current` argument.

I think it is not just `patch` which is wrong. `createOrReplace` is inherently vulnerable to race conditions. And `replace` does not in fact seem to just do a `PUT`—it does a retry on a 409 Conflict, which is wrong (you would have to retry the entire logical block starting with `GET`ting the existing object, then mutating it, then finally `PUT`ting it back); and what is worse, it seems to copy a `resourceVersion` from something it just `GET`ted to something it is about to `PUT`, which seems designed to counteract the concurrency defense [built into K8s](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency). In fact if I

```diff
diff --git a/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
index 4dc458fe..292b4944 100644
--- a/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
+++ b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java
@@ -104,9 +104,9 @@ public class HasMetadataOperation<T extends HasMetadata, L extends KubernetesRes
           @Override
           public T apply(T resource) {
             try {
-              resource.getMetadata().setResourceVersion(resourceVersion);
               return handleReplace(resource);
             } catch (Exception e) {
+              e.printStackTrace();
               throw KubernetesClientException.launderThrowable(forOperationType("replace"), e);
             }
           }
```

then things behave better in that one process does get a 409 (and in fact fails to update its part of the CR) but at least nothing gets _reverted_.

I have also seen

```
Failure executing: POST at: https://…/apis/GRP/v1/namespaces/NS/CRD. Message: resourceVersion should not be set on objects to be created.
```

though I am not sure if this is related.

**Comment by nevenr** [comment]
Hi,

We also observed strange behavior while editing kubernetes / openshift objects concurrently with fabric8 client.
In debug mode we noticed that client perform GET request followed by PATCH executing jsonpatch operations such as [{"op":"remove","path":"/userNames/12"}].
Even fact that PATCH request is executed right after GET does not helps / guaranties that concurrent update will not break consistency.

We think usage of jsonpatch test operation can be solution. http://jsonpatch.com/#test

We already checked that using curl and it works:

export TOKEN="..."
export CLUSTER_ADMIN_URL="..." 

Get object from API server:
	curl -X GET -vv -H "Authorization: Bearer ${TOKEN}" $CLUSTER_ADMIN_URL

Update object if it is not changed meanwhile:
	curl -X PATCH -vv -H "Authorization: Bearer ${TOKEN}" -H 'Content-Type: application/json-patch+json; charset=utf-8' --data '[{"op": "test", "path": "/metadata/resourceVersion", "value": "248231798"},{"op":"add","path":"/userNames/12","value":"testX@test.com"}]'  $CLUSTER_ADMIN_URL


Regards,
N.
