### ISSUE TITLE
Support Logs for Jobs

### ISSUE THREAD

**Issue by RisingPhorce** [fabric8io/kubernetes-client#1188]
I don't believe the client currently supports getting logs for a jobs.  It seems that JobOperationsImpl should have the method getLog().

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/JobOperationsImpl.java

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java

**Comment by rohanKanojia** [comment]
Yep, nice catch. It makes sense to get logs for jobs as we already have support for getting pod logs.

**Comment by SunithaR** [comment]
Any update on when getLog will be added for Jobs?

**Comment by rohanKanojia** [comment]
will try to add this feature in next release

**Comment by rohanKanojia** [comment]
@SunithaR : Hi, I've released[ v4.6.3](http://repo2.maven.org/maven2/io/fabric8/kubernetes-client/4.6.3/). It would be awesome if you could try out this newly added feature and provide some feedback whenever you get time.

**Comment by roastario** [comment]
@rohanKanojia I'm just starting integrating the new feature - will report back asap.

**Comment by rohanKanojia** [comment]
@roastario : cool, Thanks

**Comment by ktotawar** [comment]
@rohanKanojia - I am using watchLog with provided output stream for k8s jobs and I see that the stream is not populated with job logs since the pod is not ready (I see error message saying container is waiting to start in the file output stream) . If I fetch the associated pod for the job and wait for it to be ready before adding log watch then it works fine. I think the code in JobOperationsImpl which gets the associated pods for k8s job should wait for pod readiness instead of the consumer. What do you think?

**Comment by rohanKanojia** [comment]
I think you're right. We're not waiting inside the log method for Job's pods to get ready. We need to modify current `JobOperationsImpl` in order to accommodate this:
https://github.com/fabric8io/kubernetes-client/blob/8e0682230ff5b80df17f394ef36ea718745ae682/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/batch/v1/JobOperationsImpl.java#L174-L184

**Comment by ktotawar** [comment]
Right, I will create an issue and I can also work on fixing this. Thanks.
