### ISSUE TITLE
have a client.namespace(ns) method to default the namespace (returning a new client object maybe)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#123]
its kinda boring to have to keep typing `.inNamespace(foo)` in every single line of code that uses the KubernetesClient when the namespace is usually always the exact same value.

The old fabric8 client you could just set the namespace once. (e.g. in fabric8-arquillian) and you were done.

Can we try come up with a way to default the namespace somehow?

e.g. something like
```
x = client.namespace("x"); 
y = client.namespace("y"); 
ypods =y.pods().get("foo");
```

**Comment by iocanel** [comment]
@jstrachan: Way harder than it first looks. Would you like to give it a spin before I merge?

**Comment by jimmidyson** [comment]
Does this break existing clients?

**Comment by jimmidyson** [comment]
I mean the PR :-P

**Comment by iocanel** [comment]
existing clients will work fine.

**Comment by iocanel** [comment]
So this works like this:

    KubernetesClient c = new DefaultKubernetesClient();
    KubernetesNamespacedClient nc = c.inNamesapce("mynamespace");
    nc.pods().withName("pod").get();

the thing here is that the KubernetesNamespacedClient is NOT a KubernetesClient.

That's because a interface can't have a method with different return types (i.e. pods() returning the namespaced and non-namespace version of the operation).

What we could possibly do is to have OOTB the KubernetesClient return the "mixed" version the operation (that extends namespaced and non-namespaced) version of the op, but that would mean that we will need to have in the client the concept the "default" namespace to use in case the user goes:

    KubernetesClient c = new DefaultKubernetesClient();
    nc.pods().withName("pod").get(); // this client allows in all cases to bypass the namespace.

Thoughts?

**Comment by jimmidyson** [comment]
@iocanel Fixed?

**Comment by iocanel** [comment]
yes
