### ISSUE TITLE
Support async calls in Kubernects client

### ISSUE THREAD

**Issue by isunjin** [fabric8io/kubernetes-client#1245]
May be i'm missing something, do we support async calls?

**Comment by rohanKanojia** [comment]
Could you please elaborate? Isn't Kubernetes REST API is asynchronous by default?

**Comment by jivanic-demystdata** [comment]
> Could you please elaborate? Isn't Kubernetes REST API is asynchronous by default?

@rohanKanojia The question is: Is there a k8s client exposing an API which isn't blocking the thread?

Because, all the current APIs are not returning the underlying `CompletableFuture` but instead are doing `completableFuture.get()` and this is blocking the thread: https://www.baeldung.com/java-completablefuture-non-blocking#when-is-completablefuture-blocking

<img width="784" height="198" alt="Image" src="https://github.com/user-attachments/assets/ac0f8ffb-3717-4935-b3b5-1f1aa54121d6" />

<img width="746" height="318" alt="Image" src="https://github.com/user-attachments/assets/543dd3d4-0ef2-4d3c-b6d4-373370e72905" />

You should not force us to use an API which is blocking the thread and should provide an API which is exposing the `CompletableFuture<Result>`
