### ISSUE TITLE
how can i use token to access the api

### ISSUE THREAD

**Issue by littlefoolkid** [fabric8io/kubernetes-client#1378]

**Comment by littlefoolkid** [comment]
when i try ,it comes the failure:
![image](https://user-images.githubusercontent.com/34158467/53554139-1112bb80-3b7a-11e9-8c7a-6976ae2de870.png)

**Comment by rohanKanojia** [comment]
@littlefoolkid : Can you share your code? How are you passing token in config?

**Comment by littlefoolkid** [comment]
![image](https://user-images.githubusercontent.com/34158467/53554334-74045280-3b7a-11e9-8ed9-a70a54cf5bb2.png)

**Comment by rohanKanojia** [comment]
@littlefoolkid : Which version of client are you using?

**Comment by littlefoolkid** [comment]
![image](https://user-images.githubusercontent.com/34158467/53558154-6226ad80-3b82-11e9-922c-d627ebaed259.png)

**Comment by rohanKanojia** [comment]
Hm, thanks. Will try to reproduce this whenever I get time. Are you able to access cluster using default configuration(`.kube/config`) file?

**Comment by littlefoolkid** [comment]
4.0.0matches1.9
4.1.0may match 1.10

**Comment by littlefoolkid** [comment]
I don't know how to use that,could you give me an example?

**Comment by rohanKanojia** [comment]
we have a compatibility matrix: https://github.com/fabric8io/kubernetes-client#compatibility-matrix . 

Right now you're trying to access like this: https://github.com/fabric8io/kubernetes-client/blob/a7c2d1acb97e60ee6e6420bf6715a70f665612bf/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CreatePod.java#L57-L62

I am asking what happens when you try this:
https://github.com/fabric8io/kubernetes-client/blob/a7c2d1acb97e60ee6e6420bf6715a70f665612bf/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ConfigMapExample.java#L35-L36

**Comment by littlefoolkid** [comment]
Using this method, k8sclient can be successfully created

**Comment by littlefoolkid** [comment]
when I write in this method, it fails ,console print "Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring."
