### ISSUE TITLE
Support a SharedInformer API

### ISSUE THREAD

**Issue by skonto** [fabric8io/kubernetes-client#1384]
I think it would be valuable to support such an API as it exists in the [go client](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go) for writing [Operators](https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/common/AbstractOperator.java) in Java.

**Comment by skonto** [comment]
@rohanKanojia how hard would be to do this and keep things in sync with the go client. Any thoughts?

**Comment by ljnelson** [comment]
In the meantime you can see https://github.com/microbean/microbean-kubernetes-controller.

**Comment by tony-shi** [comment]
I think [kubernetes-client](https://github.com/kubernetes-client/java) is a pretty good start.  But it seems it lacks the support to CRD.
It would be awesome if this support natively so we no need to handle list and watch loop by ourselves.

**Comment by rohanKanojia** [comment]
@tony-shi : Hmm, for first draft what kind of util methods would we want to have for sharedinformer api?

**Comment by tony-shi** [comment]
I'm not a K8S pro, but from my perspective and my current use case, I think the most fundamental needs of using k8s is the caching ability.

It would be better if we have a java Reflector to automatic list the Resources in a loop, and a DeltaFIFO to de-couple the event producer and event consumer which known as cache.
The time we have a useful cache, at least we have no need to query the api-server for frequently changed resource. After this fundamental list and watch mechanism has been build natively by fabric8io/kubernetes-client, we may add indexer, Informer/SharedInformer and Controller template feature upon it.

For what i have known, the official client have such utils, but we may need to do some hack when we are using crds, since it it based on code generator. Also it is not support all the features such as add your customized indexer (at least not for now) which available in client-go . In the last, the most important thing is the way to using the official client is not quiet user friendly compared to Fabric8io/kubernetes-client.

We have see some quiet friendly packages and scaffolds  such as [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) and [apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder-alpha), however they seems all based on go language. 

Adding the caching ability then implement a user friendly Reconciler/Controller pattern would let more java users to build more sophisticated controllers/operators in their familiar ways. 

So maybe we need to implement it like below:
1. basic list and watch mechanism support, DeltaFIFO, reflector and simple cache.
2. Informer mechanism for user customization, which may include Informer, SharedInformer, EventHandler.
3. Prebuilt reconciler or controller pattern based on features before.

**Comment by ljnelson** [comment]
Seriously: have you looked at https://github.com/microbean/microbean-kubernetes-controller? There might be some ideas there. I wrote a blog series on it, too: https://lairdnelson.wordpress.com/2018/01/07/understanding-kubernetes-tools-cache-package-part-0/. Let me just say: it’s not trivial.  It is unclear to me whether it should be part of this project given its otherwise narrow focus.

**Comment by rohanKanojia** [comment]
@ljnelson : Hmm, ok. let me go through your blog today and see whether it makes sense to have it here or not.
