### ISSUE TITLE
Watch Connection leak when HTTP_GONE happens

### ISSUE THREAD

**Issue by yanzq** [fabric8io/kubernetes-client#1943]
When HTTP_GONE happens("too old resource version exception"), the web socket set to null first, the close function can not close the connection；
![image](https://user-images.githubusercontent.com/2166355/72231530-f4973a80-35f6-11ea-90a1-6e274fcbfb3d.png)

The code is in: 
File : kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java
Line : 260 
![image](https://user-images.githubusercontent.com/2166355/72231577-3e802080-35f7-11ea-982e-3affc98bf2c0.png)

line:260 should be deleted?

**Comment by yanzq** [comment]
need help?

**Comment by rohanKanojia** [comment]
Actually we removed it in past, but it caused some unwanted regressions( see https://github.com/fabric8io/kubernetes-client/pull/1800 for more details)

**Comment by kolorful** [comment]
@rohanKanojia I encountered a similar issue when using shared informers. How to reproduce:
* start a shared informer for Job and launch a Job
* stop kube-apiserver process
* restart kube-apiserver process after a few seconds
* you shall see the same error keep showing up in the logs and informer always returns true for hasSynced(), but the cache won't get any update until the next re-list.

Is it possible to let shared informer detect such issue and start a re-list? Or there is some other workaround?

**Comment by rohanKanojia** [comment]
@kolorful : Thanks for your report. I think we can add code to handle it on SharedInformer side when 410 occurs.

**Comment by kolorful** [comment]
Thank you!

**Comment by kolorful** [comment]
The other issue I observe is that informer's hasSynced() always returns true even after re-sync period is passed and re-sync failed.

How to reproduce:
* start a shared informer for Job and launch a Job and keep checking if informer is cached
* stop kube-apiserver process
* wait for the re-sync period to pass

What I expect: re-list should fail due to kube-apiserver unavailable and hasSynced() returns false.
What actually happens: hasSynced() keep returning true without the cache being updated and client has no way to catch this error and restart the informers.

It seems like in client-go you can pass a stop channel to the informer and if anything went wrong client can catch that and try restarting the informers, but we don't have that ability in java yet.

**Comment by rohanKanojia** [comment]
@kolorful : Hmm, I see. I think we should file a separate issue for this use case. WDYT? I'll try to fix these before cutting 4.7.1

**Comment by kolorful** [comment]
yes, I filed #1961 and thank you!
