### ISSUE TITLE
Upgrade Openshift model to latest versions and update openshift compatibility matrix

### ISSUE THREAD

**Issue by umutcann** [fabric8io/kubernetes-client#1990]
Hi,

Does openshift-client library has OCP 4.2 support?

Thanks.

**Comment by rohanKanojia** [comment]
Hi, I think you should be able to use our client on Openshift 4.2 without any problems. I remember I tested something on OCP 4.2 few months ago and it worked fine. Could you please try it out and share feedback about your experience with our client on OCP 4.2? We generate openshift model from https://github.com/openshift/origin + https://github.com/openshift/api  and right now model is generated at this state: https://github.com/openshift/origin/commit/0cbc58b117403b9d9169dbafdfac59ef104bb997

We used to update model with newer releases but I'm not sure why openshift folks have stopped publishing releases since 4.1 . But I think we should upgrade our model to latest master revisions.
![Screenshot from 2020-02-08 09-37-36](https://user-images.githubusercontent.com/13834498/74079001-5fe9f600-4a57-11ea-9199-f9cbd009cc55.png)

**Comment by umutcann** [comment]
Hi,

I had set up successful connection for our old OCP 3 environment before. I have only changed Openshift master URL and credential for OCP 4.2.

So I have already tried your Openshift client for our OCP 4.2 environment. But I got adaptation error like below. 

![image](https://user-images.githubusercontent.com/18632831/74124214-9d2ebf00-4be2-11ea-8870-b0986de9b9ab.png)

That's why asked your Openshift client has support for OCP 4.2.

Do you have other comment for this issue?

Thanks in advance.

**Comment by rohanKanojia** [comment]
@umutcann : Could you please share code which reproduces this error?

**Comment by umutcann** [comment]
Hi,

I added below.

 try (DefaultKubernetesClient kubernetesClient = new DefaultKubernetesClient(new ConfigBuilder()
                .withMasterUrl(masterUrl)
                .withOauthToken(authToken)
                .build())) {
            this.openShiftClient = kubernetesClient.adapt(OpenShiftClient.class);
        }

**Comment by rohanKanojia** [comment]
@umutcann : Thanks, will reproduce and fix this

**Comment by rohanKanojia** [comment]
@umutcann : Hi, Which version of Kubernetes client are you using?

**Comment by umutcann** [comment]
@rohanKanojia 4.6.4

**Comment by rohanKanojia** [comment]
@umutcann : Could you please try on 4.7.1?

**Comment by umutcann** [comment]
I got same error.

![image](https://user-images.githubusercontent.com/18632831/74125813-5abbb100-4be7-11ea-9650-987bd5f6d8cc.png)

**Comment by rohanKanojia** [comment]
ah, okay. Will fix this as soon as possible.

**Comment by rohanKanojia** [comment]
Strange, I am not able to reproduce this error. I tried on crc:
```
~/go/src/github.com/fabric8io/kubernetes-client : $ crc version
crc version: 1.5.0+e1c8fb8
OpenShift version: 4.2.14 (embedded in binary)
```

**Comment by rohanKanojia** [comment]
@umutcann : I tried with Openshift Online too but still could not reproduce this issue :confused: . Could you please check if you're missing something on your side?

**Comment by umutcann** [comment]
@rohanKanojia : Strange.

I checked that.

When I access to API URL from my browser, I could get API message like below.

![image](https://user-images.githubusercontent.com/18632831/74217221-ee5cb280-4cb7-11ea-91c7-b57e82223088.png)

But when I tried to access via your client library, I got same error message(OpenShift is not available. Root paths at:).

**Comment by umutcann** [comment]
@rohanKanojia 

It may be related witk api version of Openshift or Kubernetes.

Can we set kubernetes.oapi.version of our Openshift instance in library?

**Comment by rohanKanojia** [comment]
I'm not sure. Could you please elaborate what `kubernetes.oapi.version` property does?

**Comment by umutcann** [comment]
It explicitly specifies the location of the OAPI endpoints

**Comment by umutcann** [comment]
@rohanKanojia I solved issue.

I added .withDisableHostnameVerification(true) parameter in defining kubernetes client.

Thanks for your support.
