### ISSUE TITLE
How do I import this package with mavaen

### ISSUE THREAD

**Issue by 1542254356** [fabric8io/kubernetes-client#2154]
Can kubernetes-client be imported via maven?
Is that right?

        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
        </dependency>

But 'dependencies. Dependency. Version for IO. Fabric8: kubernetes - client: jar is missing.

**Comment by manusa** [comment]
You need to specify version tag > `<version>4.9.1</version>`

For our [examples](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/pom.xml) it works without version tag because it shares the same parent.

Check other examples online:
- https://github.com/rohanKanojia/kubernetes-client-demo
- https://github.com/rohanKanojia/kubernetes-client-inside-pod
- https://github.com/marcnuri-demo/k8s-cli-java
- https://github.com/marcnuri-demo/kubernetes-client
