### ISSUE TITLE
Missing ProjectRequestHandler since 4.1.2

### ISSUE THREAD

**Issue by matthyx** [fabric8io/kubernetes-client#2297]
Hi,
It seems that ever since https://github.com/fabric8io/kubernetes-client/pull/1322 has merged (move to code generation) the ProjectRequestHandler is missing from the io.fabric8.openshift.client jar.
Could you check it please?
Thanks!
Matthias

**Comment by rohanKanojia** [comment]
Is it possible for you to use DSL directly to create `ProjectRequest`? Actually, `ProjectRequest` doesn't seem to have any list type that's why generator skips its handler class. I checked `ProjectRequestHandler` and it seems to be having many unsupported operations:

https://github.com/fabric8io/kubernetes-client/blob/2c41816f241c1461bf980734bba88f19ac9dc3f6/openshift-client/src/main/java/io/fabric8/openshift/client/handlers/ProjectRequestHandler.java#L48-L56

**Comment by matthyx** [comment]
Well, in my use case I need to load yaml files into objects. So without the handler I am getting a NPE...

**Comment by rohanKanojia** [comment]
oh, I see. Would you like to submit a PR to fix this? I think we need to add back `ProjectRequestHandler` and add entry here:

https://github.com/fabric8io/kubernetes-client/blob/f1e892ac4908c0c54d80f875fd6109674800d5a3/openshift-client/src/main/resources/resource-handler-services.vm

**Comment by matthyx** [comment]
@rohanKanojia here you are https://github.com/fabric8io/kubernetes-client/pull/2303

**Comment by matthyx** [comment]
Thanks for your help :)
