### ISSUE TITLE
Question: How do I convert the AdmissionReview get Objects

### ISSUE THREAD

**Issue by mikebell90** [fabric8io/kubernetes-client#2326]
I have an Admission Controller set to watch create and deletes of pods. So I'd like to cast getObject, getOldObject to Pod, but can't.

I hacked this by forking this and putting in Pod, but that's lame. 

Probably missing something.

**Comment by manusa** [comment]
Maybe we can provide generics for those fields:
![image](https://user-images.githubusercontent.com/488391/87292159-afe65080-c500-11ea-83da-52dc8c77d280.png)

**Comment by mikebell90** [comment]
yes, this would significantly help. If AdmissionReview<T> existed,  one could serialize polymorphically if desired.

**Comment by shawkins** [comment]
Removing the never-stale.  

Now that there has been some additional work on handling KubernetesResource / raw we could make more proposals here.  

In particular it seems like @manusa was suggesting adding a generic parameter in places where KuberenetesResource are present.  The downside of trying to do this generally is that it will lead to warnings - e.g. WatchEvent becomes WatchEvent\<T extends KuberentesResource\>, so existing usage of unparameterized WatchEvent now has a warning.  We also don't know at generation time when there are multiple references to KuberenetesResource if they should be the same type, so we'd likely have to assume they could be different - in this case you'd have 3 generic parameters for AdmissionRequest - one for options, object, and oldObject.  So perhaps a general solution isn't warranted.

In the model project AdmissionRequest is not generated.  I believe this is due to a problem with sundrio logic - since both the v1 and v1beta1 versions are in the same module if the AdminssionRequest is buildable, it will have duplicate method signatures added to some of the builders.  This also means that we can easily make adjustments just for AdmissionRequest as a one off.
