### ISSUE TITLE
Is there a good. built in way to generate JSON Patches?

### ISSUE THREAD

**Issue by mikebell90** [fabric8io/kubernetes-client#2327]
I've got an admission controller and I wrote my own clumsy json patch generator. Works, but not very flexible. Better way?

**Comment by shawkins** [comment]
Is this just looking for a utility method based upon https://github.com/fabric8io/kubernetes-client/blob/6bb55ee2ae2ad25d477f5c1b083e04255987163c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L370 or could it be resolved based upon the various patch methods that have been added?

**Comment by shawkins** [comment]
Updating to waiting on feedback, rather than never stale.  This could be addressed by the JSON_MERGE and STRATEGIC_MERGE patch types, or a call to edit to generate the JSON patch - it's not common that a patch will need to be manually generated.  If that is a common scenario, then that likely needs to be captured by the edit/patch logic in the long term rather than exposing additional utility methods.
