### ISSUE TITLE
Access the Kuberntes API from inside the Pod  

### ISSUE THREAD

**Issue by jerryTJ** [fabric8io/kubernetes-client#2462]
create client by:
 **Config config = new ConfigBuilder().withMasterUrl(_masterUrl_).build();
 DefaultKubernetesClient client = new DefaultKubernetesClient(config);**

### sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by rohanKanojia** [comment]
I think when using client automatically detects stuff when being used from within a Pod. What happens when you won't provide any configuration?

Here is an example project I used previously to showcase How can we use Kubernetes Client from within a Pod:

https://github.com/rohanKanojia/kubernetes-client-inside-pod

**Comment by manusa** [comment]
Was the issue fixed? What JDK version are you using in your container?
