### ISSUE TITLE
io.fabric8.kubernetes.internal.InternalResourceMappingProvider not in module

### ISSUE THREAD

**Issue by takvamborgen** [fabric8io/kubernetes-client#2488]
Hi!

`jar --file=kubernetes-model-rbac-4.11.1.jar --describe-module` gives the following error:

```
Unable to derive module descriptor for: kubernetes-model-rbac-4.11.1.jar
Provider class io.fabric8.kubernetes.internal.InternalResourceMappingProvider not in module
```

Are you planning to fix this, and if so, when? :) 

Thank you.

**Comment by rohanKanojia** [comment]
ah, that's not good :-( . We'll try to fix this as soon as we can. Would it be possible for you to send us a PR to fix this? I think you would need to provide mapping for types like this:

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/knative/model/src/main/java/io/fabric8/knative/api/model/KnativeResourceMappingProvider.java

**Comment by manusa** [comment]
This is broken for all `kubernetes-model-generator` modules which contain a `src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider` descriptor with a reference to a provider not provided in the same module (namely `io.fabric8.kubernetes.api.KubernetesResourceMappingProvider`).

Probably the Service Provider configuration file was left-over in #2137/ #2108

This is the case for the following modules:
```
./kubernetes-model-discovery/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-events/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-extensions/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-metrics/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-networking/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-policy/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-rbac/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-scheduling/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-settings/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./kubernetes-model-storageclass/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
./openshift-model/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.KubernetesResourceMappingProvider
```

The `KubernetesResourceMappingProvider` is mainly used in the `KubernetesDeserializer`:
https://github.com/fabric8io/kubernetes-client/blob/6b1af63ebc23b053aacd49236930685d18b7ae82/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java#L221-L237

For the `kubernetes-model-generator`, these providers are _"not necessary"_ since there is additional logic to deserialize the model classes provided by these modules:
https://github.com/fabric8io/kubernetes-client/blob/6b1af63ebc23b053aacd49236930685d18b7ae82/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java#L251-L257

However, it would be interesting to provide module specific mappings so deserialization logic is more consistent.
