### ISSUE TITLE
Refactoring DeploymentOperationsImpl and ReplicaSetOperationsImpl in extensions/ and apps/ to avoid duplication

### ISSUE THREAD

**Issue by anshlykov** [fabric8io/kubernetes-client#2494]
Based on the discussion here https://github.com/fabric8io/kubernetes-client/pull/2409#issuecomment-678788787

**Comment by shawkins** [comment]
Removing the never-stale as there aren't great ways of doing this.  There have also been other changes that have minimized the amount of logic in these classes.  We'll likely age out the old implementations before we address this.  

For completeness, possible implementation paths include:
- introducing a base interface and builder, so that the multiple versions could share common logic - but that would require removing the generated classes and introducing a good bit of new model logic.
- switching to generic resource or reflective logic, which will be significantly uglier than what exists.
- converting the logic to make more use of overridable base logic to abstract out the differences - this is mostly what has been done and is probably what will continue to be done incrementally.
