### ISSUE TITLE
Suppress config warning

### ISSUE THREAD

**Issue by jiningh** [fabric8io/kubernetes-client#2503]
Hi,

I'm running an app outside of the cluster, everytime I make a config object the following warning happens:

`WARN  io.fabric8.kubernetes.client.Config - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.`

Obviously this wouldn't exist outside the cluster. This is my code making the client:

`val config: Config = Config.fromKubeconfig("kubectl file contents"); 
val client: KubernetesClient = DefaultKubernetesClient(config)`

I have to remake the config object everytime there is a k8s call since EKS has expiring tokens and I haven't found a better way to programatically configure it.

Everything works, it's just really annoying. Is there a way to suppress this warning?

**Comment by manusa** [comment]
Relates to: #2271

**Comment by rohanKanojia** [comment]
@jiningh : Hi, Our library uses SLF4J for logging. It can be configured to send output to a variety of destinations. Were you able to resolve this by tuning SLF4J log levels? If not, maybe we can make this line a `log.debug` statement rather than `log.warn`:

https://github.com/fabric8io/kubernetes-client/blob/f1b05115ceb7a1aef0a85f3f92cf04ddc3fa8f5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L478

**Comment by jiningh** [comment]
> @jiningh : Hi, Our library uses SLF4J for logging. It can be configured to send output to a variety of destinations. Were you able to resolve this by tuning SLF4J log levels? If not, maybe we can make this line a `log.debug` statement rather than `log.warn`:
> 
> https://github.com/fabric8io/kubernetes-client/blob/f1b05115ceb7a1aef0a85f3f92cf04ddc3fa8f5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L478

Yes, I filtered log levels to only show errors. 

Thanks!

**Comment by rohanKanojia** [comment]
@jiningh : cool, Thanks a lot!
