### ISSUE TITLE
Wildcard (*) in NO_PROXY environment variable is not honored

### ISSUE THREAD

**Issue by uklance** [fabric8io/kubernetes-client#2506]
I need to set my `https_proxy` environment variable to `http://127.0.0.1:3128` for reasons unrelated to `kubernetes-client`

The following scenario causes an error as `kubernetes-client` tries to proxy the `masterUrl` via http://127.0.0.1:3128
- masterUrl = "https://test-api.mydomain.com:6443"
- https_proxy (environment variable) = "http://127.0.0.1:3128"
- NO_PROXY (environment variable) = "*.mydomain.com"

The following scenario works since the domain is an exact match (and does not contain asterisk *)
- masterUrl = "https://test-api.mydomain.com:6443"
- https_proxy (environment variable) = "http://127.0.0.1:3128"
- NO_PROXY (environment variable) = "test-api.mydomain.com"

I believe this is related to https://github.com/fabric8io/kubernetes-client/pull/209/files

```
    private static URL getProxyUrl(Config config) throws MalformedURLException {
        URL master = new URL(config.getMasterUrl());
        String host = master.getHost();
        for (String noProxy : config.getNoProxy()) {
            if (host.endsWith(noProxy)) {
                return null;
            }
        }
        String proxy = config.getHttpsProxy();
        if (master.getProtocol().equals("http")) {
            proxy = config.getHttpProxy();
        }
        if (proxy != null) {
            return new URL(proxy);
        }
        return null;
    }
```

I think a regular expression is required instead of `if (host.endsWith(noProxy))` so that asterisk characters are wildcards

**Comment by cortex93** [comment]
I think the behavior here is to be compliant with kubectl client (more or less curl/wget pattern).

So, it is different from usual JAVA pattern.

**Comment by tom1299** [comment]
Looking at the current implementation of [getProxyUrl](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L240) I'm wondering whether something likes wildcard will work. I'm not a regex export but since `contains` is used for checking whether the actually host name is in a no proxy entry I would say that something like `*.mydomain.com` and `test-api.mydomain.com` will not work. What do you think ?
