### ISSUE TITLE
Add a warning banner that warns you about behavior differences between running on cluster vs off cluster

### ISSUE THREAD

**Issue by FWiesner** [fabric8io/kubernetes-client#2514]
We just stepped into this:

```java
k8Client.informers();
```
(from outside the cluster)

is semantically equal to
```java
k8sClient.inAnyNamespace().informers();
```
(from inside the cluster)

---
```java
k8Client.informers();
```
from inside the cluster will give you an informer just for the namespace in which you run your service.

Therefore
```java
k8Client.informers();
```
should IMHO trigger a warning banner telling you about the ambiguity.

**Comment by manusa** [comment]
If there is nothing implementation-wise specific for this, maybe it's related to the permissions of the service account used by default from Kubernetes Client when inferring the configuration from within the Pod container.

I'm not sure how we can check if we're able to infer that informers are only working for the current namespace or for all namespaces due to a permission issue.

Should the `informers()` factory implementation first check if it can access all of the namespaces and throw an error/warning if it can't. The error/warning should suggest to check the permissions of the current account in use.

**Comment by FWiesner** [comment]
The problem is that the k8s client is usable directly, without calling `inNamespace` or `inAnyNamespace`. That would be fine for cluster scoped entities. But, it works for namespaced resources as well. And then the context in which you run your app matters. In case you run it against the cluster, the client is then a `inAnyNamespace` instance. If you run it on the cluster, the client is by default a `inNamespace(<context namespace>)` instance.

**Comment by rohanKanojia** [comment]
I saw the same question on StackOverflow about this: https://stackoverflow.com/questions/64204044

I think Marc is right, this change in behavior is related to the `ServiceAccount` mounted in container.

After looking into it, looks like when inside a Pod `KubernetesClient` picks up the default namespace from `ServiceAccount` mounted volume `/var/run/secrets/kubernetes.io/serviceaccount/namespace`:
https://github.com/fabric8io/kubernetes-client/blob/aebd1f83cf2ec6c1c714cc91e609c290c01b6320/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L720-L722

When I try to override this by providing [`inAnyNamespace()`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L271) behavior(set namespace to `null`). 
```java
SharedIndexInformer<Pod> podInformer = sharedInformerFactory.sharedIndexInformerFor(
        Pod.class,
        PodList.class,
        new OperationContext().withNamespace(null), // -> Doesn't work; Ideally should Watch in all namespaces,
        30 * 1000L);
```

I don't see it getting overridden. I think we should try to make informers behave the same way when using in or outside a cluster. If it's not possible, maybe we should add a warning like Fabian said about this change in behavior and should probably provide a way to override this.

**Comment by manusa** [comment]
> If you run it on the cluster, the client is by default a inNamespace(<context namespace>) instance.

I guess this is caused here (L266):
https://github.com/fabric8io/kubernetes-client/blob/12839a5e934540061436a9551ced4655239a48f9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L263-L274

The call to `tryNamespaceFromPath` will indeed set the client's globally configured namespace:
https://github.com/fabric8io/kubernetes-client/blob/12839a5e934540061436a9551ced4655239a48f9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L721

if this file is available `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

I understand that DSL for shared informers should be clearer or at least consistent.

A) In case sharedinformers should by default be "namespaceless" then the namespace configured value in the Config should be ignored. This would mean the namespace in the Config should **always** be ignored (we will either specify it in the DSL or we'll be expecting that all namespaces are considered).

B) Or change the DSL so that it's explicit, meaning `inAnynamespace` or `inNamespace` call is always required. But this would mean breaking changes, so probably not the best fix as of now.
