### ISSUE TITLE
Cannot use deployment rolling restart API with CRUD mockwebserver

### ISSUE THREAD

**Issue by coopstah13** [fabric8io/kubernetes-client#2516]
CRUD mockwebserver attempts to perform a JSON Patch (`application/json-patch+json`) against the request, but the request is using `application/strategic-merge-patch+json` which has different semantics for the patching.

To reproduce:

- Start up a mockwebserver in CRUD mode.
- Create a deployment
- Restart deployment using below code

```
        kubernetesClient
            .apps()
            .deployments()
            .inNamespace(namespace)
            .withName(deploymentName)
            .rolling()
            .restart();
```
Results in this error in the server:
```
Sep 29, 2020 1:15:23 PM okhttp3.mockwebserver.MockWebServer$3 execute
SEVERE: MockWebServer[32923] connection from /127.0.0.1 crashed
java.lang.NullPointerException
    at io.fabric8.zjsonpatch.JsonPatch.apply(JsonPatch.java:44)
    at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.handlePatch(KubernetesCrudDispatcher.java:156)
    at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.dispatch(KubernetesCrudDispatcher.java:72)
```
Not sure what the exact algorithm would be to do this strategic merge, but seems like you would traverse all the nodes in the patch data and apply their key/value pairs to the same traversed node in the source.

**Comment by manusa** [comment]
Hi @coopstah13 
We certainly need to provide different implementations for the handelPatch method in the MockWebServer, since we are already using 2 different PATCH strategies [`application/json-patch+json`](https://github.com/fabric8io/kubernetes-client/blob/2d1a9d47d42e6aa37ba3cb0e70ede9429c93e392/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L313) & [`application/strategic-merge-patch+json`](https://github.com/fabric8io/kubernetes-client/blob/2d1a9d47d42e6aa37ba3cb0e70ede9429c93e392/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L334).

I'm not sure how soon we'll be able to tackle this. Maybe you could provide a PR if you have time ;)
