### ISSUE TITLE
Support for cert-manager model in fabric8

### ISSUE THREAD

**Issue by PrakashNair** [fabric8io/kubernetes-client#2565]
Does the client library provide support for cert-manager CRDS (https://github.com/kubernetes-client/java/tree/master/client-java-contrib/cert-manager#cert-manager-model-classes)? 
if yes, can you provide some pointers/examples on its usage? if no, are there any plans on extending the library to support it?

**Comment by rohanKanojia** [comment]
@PrakashNair : Umm, Could you please share location of these cert-manager-model go structs? Maybe we can write a quick extension for these CRDS(like we have for Knative, Tekton, Istio etc)

**Comment by rohanKanojia** [comment]
Thanks a lot for sharing! We can easily extend Kubernetes Client to create extensions. Writing an extension just involves these steps:

1. Generating model schema(certmanager-schema), You can use our common model generator to generate schema for Java classes for these go structs. Here is an example of our VolumeSnapshot Extension model generator: https://github.com/fabric8io/kubernetes-client/blob/master/extensions/volumesnapshot/generator/cmd/generate/generate.go#L33
2. Generating Java model(certmanager-model): This JSON schema would be used by JSONSchema2POJO to generate POJOs for these resources. You can check VolumeSnapshot Extension model for this: https://github.com/fabric8io/kubernetes-client/blob/master/extensions/volumesnapshot/model/pom.xml#L105 
3. Writing a simple Client Extension on top of the above-generated model which would inheric Fabric8 Kubernetes Client's base client: 
https://github.com/fabric8io/kubernetes-client/blob/master/extensions/volumesnapshot/client/src/main/java/io/fabric8/volumesnapshot/client/DefaultVolumeSnapshotClient.java
https://github.com/fabric8io/kubernetes-client/blob/master/extensions/volumesnapshot/client/src/main/java/io/fabric8/volumesnapshot/client/VolumeSnapshotClient.java

Would you like to contribute a PR in order to fix this? I think it would be awesome if we could get a contribution to this issue. You can check out these PRs to get an idea of how things are connected:

ChaosMesh (Under Review) : https://github.com/fabric8io/kubernetes-client/pull/2556
CSI VolumeSnapsho(Merged): https://github.com/fabric8io/kubernetes-client/pull/2356

**Comment by rohanKanojia** [comment]
We don't have any bot for assigning issues :laughing: . 

Thanks a lot for taking care of this issue.

**Comment by matthyx** [comment]
@rohanKanojia @arghya88 are you both still interested into supporting these CRDs? Do you need my contribution?

**Comment by rohanKanojia** [comment]
I think we should definitely add support for this. ping @arghya88 Are you still working on this?

**Comment by rohanKanojia** [comment]
@matthyx : Hi, Do you want to work on this issue? I can try picking this up in next sprint.

**Comment by matthyx** [comment]
@rohanKanojia I have started to put the golang files into a branch... and see how they work. So nothing too advanced atm, but I can try to make it work for you :)

**Comment by rohanKanojia** [comment]
@matthyx : Awesome, Thanks a lot!. Feel free to ping me on Gitter[0] in case you face problems with anything.

[0] https://gitter.im/fabric8io/kubernetes-client
