### ISSUE TITLE
Ingress is not handled by the client

### ISSUE THREAD

**Issue by jonathanvila** [fabric8io/kubernetes-client#2620]
Trying to execute this with the client : 
    kubectl get ingresses.config.openshift.io cluster -o json

Request : 
   GET https://api.windup.eb23.sandbox1661.opentlc.com:6443/apis/config.openshift.io/v1/ingresses/cluster

Apparently client has `config.openshift.io/v1` resources added in DSL but Ingress is not there.

**Comment by rohanKanojia** [comment]
Hmm, I think in order to fix this we might need to refactor go generator a bit to consider apiGroups and apiVersions along with name since `networking.k8s.io/v1#Ingress` is Namespaced resource and `config.openshift.io/v1#Ingress` in Cluster scoped:

https://github.com/fabric8io/kubernetes-client/blob/2cca1ebac05cfb3211530cc6a7cbb2e9382e94f0/kubernetes-model-generator/pkg/schemagen/generate.go#L563

**Comment by jonathanvila** [comment]
**workaround :**
```
CustomResourceDefinitionContext customResourceDefinitionContext = new CustomResourceDefinitionContext.Builder()
      .withName("Ingress")
      .withGroup("config.openshift.io")
      .withVersion("v1")
      .withPlural("ingresses")
      .withScope("Cluster")
      .build();
      Map<String, Object> clusterObject = k8sClient.customResource(customResourceDefinitionContext).get("cluster");
      HashMap<String,String> objectSpec = (HashMap<String,String>) clusterObject.get("spec");
 
     log.info("Domain got : " + objectSpec.get("domain"));
 ```
This is a more appropiate way to obtain the external URL of the cluster compared with ( this one fails in some environments like Katacoda ): 
```
      ConfigMap configMap = k8sClient.configMaps().inNamespace("openshift-config-managed").withName("console-public").get();
```
