### ISSUE TITLE
Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, DeploymentConfig, ReplicationController], but was: [Service] 

### ISSUE THREAD

**Issue by Eddman** [fabric8io/kubernetes-client#2672]
We're watching service readiness using following code:
```java
final Service service = this.kubernetesClient
                        .services()
                        .inNamespace(namespace)
                        .withName(name)
                        .waitUntilReady(60, TimeUnit.SECONDS);
````
We used this code with version `4.6.0` and it worked.
After upgrading to version `4.13.0` it stopped working with the following exception:
```
java.lang.IllegalArgumentException: Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, ReplicationController], but was: [Service]
	at io.fabric8.kubernetes.client.internal.readiness.Readiness.isReady(Readiness.java:62)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$waitUntilReady$6(BaseOperation.java:1109)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilConditionWithRetries(BaseOperation.java:1131)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:1115)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:1109)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:83)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:37)
```

**Comment by rohanKanojia** [comment]
Umm, I think a `Service` should be ready whenever it gets created. I don't think it's a Ready-able resource

**Comment by Eddman** [comment]
Original implementation of `ServiceOperationsImpl.waitUntilReady` in `4.6.0` waited for condition `notNull` for the Service and then waited for Endpoints to become ready. Now it just fails calling `super.waitUntilReady()` that has been changed somewhere between `4.6` <-> `4.13`.

**Comment by rohanKanojia** [comment]
ohk, I see. You're right, there is an implementation in `ServiceOperationsImpl.waitUntilReady`(I wasn't aware of this):

https://github.com/fabric8io/kubernetes-client/blob/69bd3622dc7af5665c75798deb946f7b9f8c27c6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java#L79-L90

I think we might have broken this while refactoring waitUntilCondition to use watcher instead of polling (https://github.com/fabric8io/kubernetes-client/pull/2239) . In v4.6.0 version of `waitUntilReady` I don't see `Readiness.isReady` being used too (which might be the reason waitUntilReady worked fine)

Since `Service` depends on `Endpoints` to become ready, maybe we can add this to our Readiness applicable resources:
https://github.com/fabric8io/kubernetes-client/blob/69bd3622dc7af5665c75798deb946f7b9f8c27c6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L46-L56

**Comment by manusa** [comment]
This behavior describes some sort of integrated Readiness Probe, meaning both the Service and the Pod are ready.

So as a workaround, given that a valid Service configuration is provided, `pods().whatever().isReady()` should do the job.

Adding this to the `isReadinessApplicable` classes won't work as this **requires** polling (unless there's a different/inconsistent implementation for each resource). The watcher will only get `MODIFIED` events with status (spec too, but not applicable here) updates to the Service resource. Since the service status won't change, the endpoint check will never be triggered.

IMO I don't think that `services().whatever().isReady()` is a good name for what this does (unless kubectl/client-go/some k8s spec defines this as `ready`). Maybe something like `services().whatever().ports().waitUntilReady()` or `services().whatever().probe()` + `services().whatever().waitUntilProbe()` or anything in those lines, helps other users understand and set proper expectations.

**Comment by Eddman** [comment]
So the original behavior was:
1. wait for `Service` creation `.waitUntilCondition(Objects::notNull, ...)` (called from `waitUntilReady()`
2. wait for `Service` `Endpoints` to be ready `endopints().waitUntilReady(...)`

But now `waitUntilReady()` for unknown objects throws exception instead of calling `.waitUntilCondition(Objects::notNull, ...)`

Somehow it makes sense cause we can wait for `Service` to have ready `Endpoints` 🤷‍♂️ Once ready we can call that service without worrying that some child components (`Endpoints`, `Pods`) are not ready...

**Comment by manusa** [comment]
Yes, I agree with the usefulness of the method, but not sure if the name + DSL access methods align with what it does.

**Comment by manusa** [comment]
From: https://github.com/fabric8io/kubernetes-client/pull/2796#issuecomment-777497232

---

Given that [ServiceOperationsImpl](https://github.com/fabric8io/kubernetes-client/blob/1e1fdb81eabf92e6905f2d4e07c80e472d78bc75/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java) extends [BaseOperation](https://github.com/fabric8io/kubernetes-client/blob/0c4513ff30ac9229426f1481a46fde2eb54933d9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java) which in turns implements the [Resource](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Resource.java) interface which extends the [Readiable](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Readiable.java) and [VersionWatchAndWaitable](https://github.com/fabric8io/kubernetes-client/blob/0b84591916ec5ce6aaa98827cfe3658219d33b5d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/VersionWatchAndWaitable.java) interfaces, the [Readiness#isReady ](https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L58) method, should **never** throw an Exception.

The fact is that from our current DSL point of view, we consider every Resource as waitable/readiable, so waitUntilReady() method is generated for all resources. This means that calling this method for any of the Resources that aren't currently handled in the Readiness#isReady method will throw an exception. 

https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L66-L85

https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L58-L64

The fix should be to replace line 62 by an existence check Objects:nonNull of a resource retrieved from the server, and **maybe** warn the user about the resource not being of what **we** consider of a "RediableKubernetesResource" type.
