### ISSUE TITLE
Potential CVE?

### ISSUE THREAD

**Issue by ibodrov** [fabric8io/kubernetes-client#2715]
A recently found [vulnerability](https://seclists.org/oss-sec/2021/q1/19) was fixed in [another project](https://github.com/kubernetes-client/java/issues/1491) similar to this one. It might potentially affect [a similar implementation](https://github.com/fabric8io/kubernetes-client/blob/c9bf95da45f2560a7be7651fc37db5257c5418b1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java#L563) in `PodOperationsImpl`.

Ironically, [it prints out the normalized path](https://github.com/fabric8io/kubernetes-client/blob/c9bf95da45f2560a7be7651fc37db5257c5418b1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java#L574) into stdout, but uses the original (potentially dangerous) path.

**Comment by manusa** [comment]
I finally managed to create a reproducer for this CVE.

I first created a [Container Image](https://github.com/manusa/docker-images/tree/master/poisoned-tar) which contains a [poisoned tar](https://hub.docker.com/r/marcnuri/poisoned-tar) binary.
Whenever this binary is executed with arguments `-cf - [fileName]` it will produce a tar with a single [file containing a forged tar](https://github.com/manusa/docker-images/blob/dd0a5a7c3567f92bb61b187f16bc448ee9ec15db/poisoned-tar/src/main/java/com/marcnuri/infosec/Application.java#L13) entry `../youve-been-hacked`.

The [following gist](https://gist.github.com/manusa/94b91311ee9af7267a8a7f659f594a82) contains a [JBang](https://www.jbang.dev/) script that will exploit the vulnerability.
You should be able to invoke the script by running the following in your command line:
```
$ jbang https://gist.github.com/manusa/94b91311ee9af7267a8a7f659f594a82
```

This is an excerpt of the script:
```java
final Path targetDirectory = Paths.get("", "target-directory");
targetDirectory.toFile().mkdirs();
kc.pods().withName(podName).dir("/var/lib").copy(targetDirectory);
```
According to this script, the contents of the container's `/var/lib` directory should be copied to the local `./target-directory`. 

However, when the script is executed, a file `youve-been-hacked` is created in the parent directory (since the tar entry is defined as `../youve-been-hacked`, thus exploiting the exposed vulnerability.

If you were to extract this intermediate tar using the standard tar command, you would be greeted with the following error:
```
tar: Removing leading `../' from member names
tar: ../youve-been-hacked: Member name contains '..'
tar: Exiting with failure status due to previous errors
```
You would need to force the extraction using the `-P`/`--absolute-names` (don't strip leading '/'s from file names)
 flag

**Comment by manusa** [comment]
Releases with fix:
- [5.0.2](https://github.com/fabric8io/kubernetes-client/releases/tag/v5.0.2)
- [4.13.2](https://github.com/fabric8io/kubernetes-client/releases/tag/v4.13.2)
- [4.7.2](https://github.com/fabric8io/kubernetes-client/releases/tag/v4.7.2)
