### ISSUE TITLE
Event model and api mismatch.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2837]
It seems that `client.v1().events().list()` return `io.fabric8.kubernetes.api.model.Event` while I would expect it to return it's v1 variant.

**Comment by rohanKanojia** [comment]
Umm, `client.v1().events()` provides `Event` class from [`kubernetes/api`](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5403) (which is used in `kubectl get events`). Are you talking about `events.k8s.io/v1#Event` ?

**Comment by iocanel** [comment]
I would expect `v1().events()` to operate on `events.v1`, is my assumption wrong?

**Comment by manusa** [comment]
As Rohan says, this DSL [`v1()`](https://github.com/fabric8io/kubernetes-client/blob/17ae0977e8f7b22177fd3f4447d4b36cb9b7d36c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L495) points to core.v1 K8s API.
The `events()` method within the [V1APIGroupDSL](https://github.com/fabric8io/kubernetes-client/blob/17ae0977e8f7b22177fd3f4447d4b36cb9b7d36c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1APIGroupDSL.java#L24) provides access to the [Event v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-core) resource (`/api/v1/namespaces/{namespace}/events`). 

I think you are referring to the v1 Events API introduced in [Kubernetes 1.19](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-events-k8s-io).

> I would expect v1().events() to operate on events.v1, is my assumption wrong?

My assumption would be to access the events API through `events().v1()` or `events().v1beta1()`, but unfortunately those interfaces are missing :(. Also the model package/module should be different too.

---

So just to be clear, since this confuses many users and we probably need to figure out a way to make it clearer:
- There are events in the core.v1 K8s API
- There are events in the events.v1 and events.v1beta1 K8s API (apparently, currently unsupported)
- There are `WatchEvent`s provided by the [Watch REST API spec](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes).
