### ISSUE TITLE
The client doesn't seem to respect insecure-skip-tls-verify

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2888]
To elaborate, the `insecure-skip-tls-verify` is correctly read.
`Config.isTrustCerts()` correctly returns `true` when the option is present.
However, we still get errors when certs cannot be verified.

Related: https://github.com/java-operator-sdk/java-operator-sdk/issues/366

**Comment by manusa** [comment]
Are those errors happening in JVM mode or only in native?

I had lots of issues dealing with OpenShift 4.x SSL and native builds of Quarkus projects.

**Comment by lburgazzoli** [comment]
JVM mode

**Comment by rohanKanojia** [comment]
Hello guys, I'm trying to reproduce this issue on OpenShift v4.7.2 (crc v1.24.0). But somehow I'm not able to reproduce it, for me it seems to be working correctly(or maybe I'm missing something). Here is what I'm doing:

When I create a fresh new cluster with a clean kubeconfig file, which doesn't have `insecure-skip-tls-verify` set and run a simple code like this:
```java
try (KubernetesClient k8s = new DefaultKubernetesClient()) {
  logger.info("TrustCerts: {}", k8s.getConfiguration().isTrustCerts());
  logger.info("Certificate: {}", k8s.getConfiguration().getCaCertData());
  k8s.pods().inNamespace("openshift-console").list()
      .getItems()
      .stream()
      .map(Pod::getMetadata)
      .map(ObjectMeta::getName)
      .forEach(logger::info);
}
```
It works and prints the following:
```
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - TrustCerts: false
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - Certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F(trimmed)
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - console-7985f9d77f-8vwpd
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - console-7985f9d77f-b7ds6
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - downloads-6df577f985-hdv4r
```

In order to get certificate validation failures, I trimmed first two characters from `certificate-authority-data` in `.kube/config`. After this I was able to see some error related to certificates.

But when I add `insecure-skip-tls-verify: true` in my `.kube/config` it starts working again. `config.isTrustCerts()` was also set correctly:
```
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - TrustCerts: true
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - Certificate: 0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lJS3p2ZURscHdZTkV3R
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - console-7985f9d77f-8vwpd
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - console-7985f9d77f-b7ds6
[main] INFO io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent - downloads-6df577f985-hdv4r
```

**Comment by lburgazzoli** [comment]
I'm using this in the context of an Java Operator with Quarkus, which may configure the client in a different way.

**Comment by iocanel** [comment]
@rohanKanojia: I haven't been able to reproduce in a unit test either. The config seems to be read correctly. I am pretty sure though that there  might be an edge case, where the read value is not properly applied.
