### ISSUE TITLE
Gracefully handle the case that the metdata object is null

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2927]
Right now a user is able to create an object with no metadata.

Some examples:

- client.pods().create(new PodBuilder().build());
- client.resource("apiVersion: v1 kind: Pod").watch(...);
- and so on.

However, the client code always assumes that `metadata` is present.
This can cause NPEs.

We need to support the case where `metadata` is actually null.

**Comment by rohanKanojia** [comment]
Related to https://github.com/fabric8io/kubernetes-client/issues/2802

**Comment by manusa** [comment]
There are valid cases where `HasMetadata` resource implementations can have null metadata (such as PATCH operations).

Could you elaborate a little bit more on your proposal.

- For your first example `client.pods().create(new PodBuilder().build());` a null metadata should not be feasable since for the POST method operation we need to provide a name for the resource. Are you talking about adding client side validations?
- For the second `client.resource("apiVersion: v1 kind: Pod").watch(...);` metadata should be necessary if and only if `inNamespace`and `withName` options were not specified.

**Comment by iocanel** [comment]
For the first example, we should throw a meaningful error.
For the second, metadata should not be necessary as its perfectly fine to somehow request watching all resources of the specified kind.
