### ISSUE TITLE
Debug messages in CustomResource logged too often

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3057]
setApiVersion and setKind have debug messages which are likely intended for scenarios where the methods are explicitly called - but when you are relying upon deserialization they are also called by jackson.  For lots of objects this can dominate the debug log.

**Comment by manusa** [comment]
Relates to #2683, #2661  

This was very lightly discussed in #2661.

Does it make sense to log anything at all in any context?
IMHO a warning might make sense because if these methods are explicitly called by developers, something should warn them that it won't have any effect.
However, seeing the current usage and approaches, what might make more sense is just to provide more specific JavaDoc with a warning about the NOOP implementation, and remove the log.

**Comment by shawkins** [comment]
If you want to keep the log, consider #3059

I'm fine with removing it as well.
