### ISSUE TITLE
What exceptions should cause informers to not start/terminate

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3073]
Now that a informer will attempt to indefinitely reconnect, it should be asked - what conditions should cause an informer to fail to start or terminate re-connection attempts?  For example currently if the initial list/watch fails, then the informer will fail to run - this doesn't seem to match the later behavior of continuing to retry.

**Comment by shawkins** [comment]
cc @rohanKanojia @manusa WDYT?

**Comment by manusa** [comment]
I'm not really sure what kind of Exceptions we can identify with precision.

The current behavior makes sense (for me) in an hypothetical case where there might be an intermittent network/cluster access failure. An initial informer failure when there is no network is important so that the user can take immediate action (it's probably an indication of a non-intermittent network failure/cluster access problem/...).
But if the initial Shared Informer phase succeeded, it does make sense to keep retrying for a "while" in case it is indeed an intermittent failure (this "while" is what might be unclear). If I'm not mistaken, in the current state, we'll keep retrying forever, which might not be something desirable. So maybe being able to configure this "retry for a while" should be something useful.

In any case, our implementation should more or less do exactly what client-go does, which I'm completely unaware of.

**Comment by shawkins** [comment]
> If I'm not mistaken, in the current state, we'll keep retrying forever, which might not be something desirable.

Yes, that is what I'm asking here as well - what should terminate that if anything.

> So maybe being able to configure this "retry for a while" should be something useful.

Right now re-connecting informer watches are not subject [1] to the reconnect limit [2].  It doesn't appear that they have a limit in in the go code.

[1] https://github.com/fabric8io/kubernetes-client/blob/e11be3785da1f53cb75331262358b4eb72d6d867/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java#L124
[2] https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RequestConfig.java#L45

> In any case, our implementation should more or less do exactly what client-go does, which I'm completely unaware of.

If I'm reading things correctly, it will try forever to establish the watch: 
https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/tools/cache/reflector.go#L392
And exit that loop if it's been explicitly stopped (we do this also):
https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/tools/cache/reflector.go#L396
If the watch fails for a reason other than connection refused (we do not do this):
https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/tools/cache/reflector.go#L424

**Comment by shawkins** [comment]
I think I'm good with the current state of things with this issue.  If we successfully start the informer, we'll just keep retrying.  A possible refinement to the watch retry logic would be an exponential backoff rather than the interval setting.  

There is also #3143 and the pending work for #3090 that will provide even more information and control over what has happened with the informer.
