### ISSUE TITLE
How to synchronise watcher better multiple services running Fabric8 Client

### ISSUE THREAD

**Issue by krishadvani** [fabric8io/kubernetes-client#3115]
Currently, I am listening events in a namespace with the below-mentioned script in a pod within the cluster, which has multiple replicas, however, the watcher executes on each and every replica running the service, since there is no intercommunication between them. 

Is there a way to synchronize them or the only option is to run this without any replicas?

```
this.watch = client.batch().jobs().inNamespace(K8Constants.NAMESPACE).watch(new Watcher<Job>() {

			@Override
			public void onClose(WatcherException cause) {
				log.error("Watcher failed due to {}", cause.getCause());
				watcherMethod();
			}

			@Override
			public void eventReceived(Action action, Job resource) {
				log.info("Name {} with status {} with action {}", resource.getMetadata().getName(),
						resource.getStatus(), action);
			}
		});
```

**Comment by manusa** [comment]
AFAIK (I can't find a reference now), operators are designed under the assumption that only one Pod will be running at any time (maybe someone else can provide the missing reference or refute this statement).

In your case, one of the options would be to implement a singleton pattern so that only one of the Pods acts as a leader and is the only one watching. Our client offers a possible solution for this via the leader election, [see examples](https://github.com/fabric8io/kubernetes-client/blob/1074cc26884e869921fb3787cbc12ec16f334a4f/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java). There are frameworks that provide similar solutions too.

Another option, would be to design your watcher with concurrency in mind in a way that it doesn't matter if more than one instance is running at any time. This is what I personally prefer because it makes the system more resilient (IMHO) and easier to configure, deploy and maintain.

**Comment by krishadvani** [comment]
Hi @manusa thanks a lot for your insight, I implemented watchers while handling concurrency in the microservices, thanks a lot for your assistance, really appreciate it.
