### ISSUE TITLE
KubernetesServer in CRUD mode does not handle resourceVersion properly

### ISSUE THREAD

**Issue by scootafew** [fabric8io/kubernetes-client#3255]
I'm currently writing an Operator, and have the following logic on my event handler to prevent doing pointless reconciliation when there are no changes.

```java
  @Override
  public void onUpdate(ConfigMap oldConfigMap, ConfigMap newConfigMap) {
    if (oldConfigMap.getMetadata().getResourceVersion().equals(newConfigMap.getMetadata().getResourceVersion())) {
      LOGGER.info("Skipping UPDATE for ConfigMap ({}), nothing changed...", newConfigMap.getMetadata().getName());
      return;
    }

    enqueue(newConfigMap);
  }
```

However when writing my tests with KubernetesServer in CRUD mode this does not work as the server never increments the resourceVersion on updates - it is always "1".

**Comment by rohanKanojia** [comment]
We're not handling resourceVersion properly. It is hardcoded to 1 as you mentioned already: 
https://github.com/fabric8io/kubernetes-client/blob/5bfcac2d8a144f66b1323df5988dd2761fc7e561/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java#L444

Do you have some approach in mind to handle this? I haven't really investigated but maybe it's possible to generate a random value and setting that as resourceVersion instead of hardcoding `1`.

**Comment by scootafew** [comment]
Yes, I was thinking a random value should work to ensure an equals check fails. However, I wasn't sure if there is ever a case where the value's are compared as integers, e.g.

```java
if (newResourceVersion > oldResourceVersion) {
  ...
}
```

It's also possible that it could be left up to the user to increment the resource version when updating a resource, but even that doesn't seem to work at the moment, as no matter what I manually set it to before the API call it is always 1 on the server.

**Comment by shawkins** [comment]
It looks like you are using an Informer / ResourceEventHandler - if that's the case are you also specifying a resync?  If you don't otherwise have a need for it, just turn the resync off and you'll stop getting events like these - resync events are updates where nothing has actually changed.

It's a todo of mine to eventually support the resource version in the mock crud server, but it should also be supported in list/watch to work more fully.

**Comment by scootafew** [comment]
Yep that's right, I have specified a resync as I was under the impression that would help to ensure no events are missed, or rather that the state is eventually consistent. But it's a good point thanks, for now I will dig a bit deeper to see if I do need the resync, or if there is some other workaround I can do.

**Comment by shawkins** [comment]
> Yep that's right, I have specified a resync as I was under the impression that would help to ensure no events are missed, or rather that the state is eventually consistent.

I had the same initial impression based upon the older fabric8 code, 5.1.1, our project started working with - there the resync was also causing a new list/watch.  However subsequently that has been removed as it was found to be problematic and not consistent with the go client.  Now resync is just a about creating those non-update update events on a periodic basic - it doesn't do anything to the state or watch.

**Comment by scootafew** [comment]
Ah ok that's very useful to know, thanks @shawkins!
