### ISSUE TITLE
isReady logs a warning when null

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3307]
If I do something like: pods().inNamespace...withName...isReady() - I'll see a warning log and a false result when null.

Should isReady return null when the resource is null?

**Comment by rohanKanojia** [comment]
I'm not sure about this, since this method is named `isReady()` user's expectations are set to be a boolean value. I'm not sure if we should return null in this case.

**Comment by shawkins** [comment]
The interface is already defined as Boolean isReady - if a null result is not possible, it should just be boolean.

**Comment by shawkins** [comment]
The two proposals would be:

1. return isReady null when the resource is null, with no associated logging.  This could be seen by some users as a breaking change, but does conform to the existing interface.
2. Change the interface to boolean isReady and throw a ResourceNotFoundException when the resource is null.  This also would be a breaking change, but it would force the caller to handle the null situation rather than logging it.

**Comment by manusa** [comment]
I don't like the null return value, especially with your depicted scenario.

Users implementing (for whatever reason) a manual version of `client.pods().inNamespace...withName...waitUntilReady(...)`, are probably expecting that statement to return false, since there is no resource available+ready matching that name+namespace.

So (IMHO) I see option 2 as the valid way, but excluding the ResourceNotFoundException

**Comment by shawkins** [comment]
The root of the problem is: https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L123

waitUntilReady does a null check before calling isReady(resource)

https://github.com/fabric8io/kubernetes-client/blob/b9c54190073c5c099036806af7c92a9fde66e738/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L962

So you are saying just do the same for isReady() - https://github.com/fabric8io/kubernetes-client/blob/b9c54190073c5c099036806af7c92a9fde66e738/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L957

And update the interface boolean and javadocs to indicate that missing means not ready - I'm fine with that resolution as well.  My impression from some of the logic that we wanted users to be aware that the value was null.

**Comment by manusa** [comment]
I specifically mentioned the `waitUntilReady` method because I'm aware that some users from 4.x versions might have a downstream implementation relying on the isReady method. But yes, my opinion is that both methods should be consistent.

I don't know why a `Boolean` was chosen as the return value instead of `boolean` in the first place. For me this is semantically confusing (thing are either ready or not), and might complicate things downstream.

Related to:
- #2796
- #2838
- #2718
- #2557
- #2452
