### ISSUE TITLE
Deprecate DSL Methods/Kubernetes Resources which are going to be removed in Kubernetes 1.22

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3338]
We need to deprecate these methods in upcoming release so that we can safely delete them in next to next release. These types are no longer available in Kubernetes 1.22, see https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

- `client.admissionRegistration().v1beta1()`
- `client.apiextensions().v1beta1()`
- ` client.authorization().v1beta1()`
- `client.certificates().v1beta1()`
- `client.extensions().ingresses()`
-  `client.network().v1beta1().ingresses()`

Related to https://github.com/fabric8io/kubernetes-client/issues/3326

**Comment by manusa** [comment]
Why would we want to delete them?

Consider the case of someone using the latest Kubernetes Client version to access an older cluster.

The good thing about having DSL accessors with versions is that we can keep them and have a broader compatibility matrix.

The question is if keeping this is compatible with the current golang generator project.

**Comment by manusa** [comment]
OK, I read delete instead of deprecate. Deprecate with message makes sense.

**Comment by rohanKanojia** [comment]
ohk, we will need to split kubernetes-model-generator into smaller version-specific generators with their own `go.mod` in order to keep both new and old versions

**Comment by manusa** [comment]
> ohk, we will need to split kubernetes-model-generator into smaller version-specific generators with their own `go.mod` in order to keep both new and old versions

Then we need to check which of the types makes sense to keep. Resources which have had a non-beta/alpha release for more than a year might not be worth the extra-effort + module cost.

**Comment by jorsol** [comment]
The problem with deprecating is that it might confuse users, the difficult part is that it actually depends on the server version at runtime while the client still supports older clients.

It's a chicken-egg problem... if you run on K8s v1.18 `client.certificates().v1beta1()` is perfectly fine and actually is the only valid option since `client.certificates().v1()` is available since v1.19, and if you run on v1.22 the only valid option is `client.certificates().v1()`, and in between both are valid, so, unless KC drop supports for older K8s versions, then it doesn't make sense to drop/deprecate methods that are actually depending on a "supported" K8s version, if you tell me for instance that KC 5.x works from 1.16 an up, then yes, deprecate and delete everything that is below 1.16, but if the intention is to support way older versions like 1.11, then all APIs since that version should be also available.

**Comment by rohanKanojia** [comment]
Kubernetes 1.22 got released last night. We should prioritise deprecating these methods so that we can get this in v5.7.0

**Comment by rohanKanojia** [comment]
@jorsol : sorry, i didn't see your comment. Right now our model seems to reflect a specific version of kubernetes.

If we don't want to deprecate we may need to split java and go modules to maintain different versions.

**Comment by jorsol** [comment]
>  Right now our model seems to reflect a specific version of kubernetes.

Yes, that's what I thought, but in that case, the compatibility matrix might not be valid: https://github.com/fabric8io/kubernetes-client#kubernetes-compatibility-matrix

Yet, if deprecating doesn't mean removal, it may be ok, as I said, it's a chicken-egg problem, `kubectl` and k8s components handle this by following a [Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/) of  +1/-1 of the supported version, (For example, if your kube-apiserver is at 1.17, then you can use versions 1.16 to 1.18 of kubectl with that kube-apiserver.), but that limits a lot the use of fabric8 client, other clients follows this policy (the official java, python and javascript):

> The Kubernetes cluster has no guarantees to support the API client of this version, as it only promises n-2 version support.

So, that might mean that newer fabric8 client version could not be fully compatible with the oldest K8s cluster, I'm not saying that the project should support super old versions of K8s, but n-2 is still very limited for many uses cases.

Anyway, whatever is the path to follow, the compatibility matrix might need a makeup to reflect the supported version policy.

**Comment by manusa** [comment]
Personally I believe that as long as we can we should provide full backwards compatibility, given the versioned nature of the Kubernetes HTTP API, it should be possible.
However, since we have this Go->JsonSchema->Java->APTprocessedJava process, it might be hard to keep compatibility with every resource. Also our current module organization doesn't help much in that area.
So, as long as it's not very hard to maintain, [we should keep them](https://github.com/fabric8io/kubernetes-client/issues/3338#issuecomment-884121799).
