### ISSUE TITLE
Improve `io.fabric8.kubernetes.client.mock.ErrorMessageTest` to use assertThrows

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3355]
Right now ErrorMessageTest.testCustomMessage is written in a strange way. 
- Instead of using `assertThrows` we're catching an exception. 
- There is a custom `fail()` method that does nothing.
- We're not asserting anything, see sonar smell here[0]

https://github.com/fabric8io/kubernetes-client/blob/d1740ffeaa624bd63b6d929b25d764a477c1c17e/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ErrorMessageTest.java#L48-L55

I think we can improve this test by using assertThrows and assertThat correctly, Here is an example for `testCustomMessage`:
```java
@Test
void testCustomMessage() {
  // Given
  client.getConfiguration().getErrorMessages().put(HttpURLConnection.HTTP_FORBIDDEN, "MSG");
  server.expect().withPath("/api/v1/namespaces/test/events").andReturn(200, new io.fabric8.kubernetes.api.model.EventListBuilder()
    .addNewItem()
    .withNewMetadata()
    .withName("event1")
    .endMetadata()
    .endItem().build()).once();
  server.expect().withPath("/api/v1/namespaces/test/events/event1").andReturn(403, Boolean.FALSE).once();

  // When
  NonNamespaceOperation<Event, EventList, Resource<Event>> eventOp = client.v1().events().inNamespace("test");
  KubernetesClientException k8sException = assertThrows(KubernetesClientException.class, eventOp::delete);
  
  // Then
  assertThat(k8sException.getMessage())
    .contains("Message: MSG")
    .startsWith("Failure executing: DELETE")
    .doesNotContain("Received status");
}
```

- [ ] Refactor `ErrorMessageTest.testCustomMessage` like shown above
- [ ] Refactor `ErrorMessageTest.testServerErrorWithStatus` following similar pattern

[0] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS2970

**Comment by KamalSinghKhanna** [comment]
so if I am not wrong, I have to change  this 
`Assertions.assertThat(e.getMessage().startsWith("Failure executing: DELETE")); 
   Assertions.assertThat(e.getMessage().contains("Message: MSG")); 
   Assertions.assertThat(not(e.getMessage().contains("Received status"))); `
to this 
`assertThat(k8sException.getMessage())
    .contains("Message: MSG")
    .startsWith("Failure executing: DELETE")
    .doesNotContain("Received status");`

**Comment by rohanKanojia** [comment]
Yeah, you're right.

**Comment by KamalSinghKhanna** [comment]
You mean 

`// When
  NonNamespaceOperation<Event, EventList, Resource<Event>> eventOp = client.v1().events().inNamespace("test");
  KubernetesClientException k8sException = assertThrows(KubernetesClientException.class, eventOp::delete);
  
  // Then
  assertThat(k8sException.getMessage())
    .contains("Message: MSG")
    .startsWith("Failure executing: DELETE")
    .doesNotContain("Received status");
}`  
instead of  
   
` try{ 
   client.v1().events().inNamespace("test").delete(); 
   fail(); 
 } catch (Exception e){ 
   System.out.println("exception: "+e); 
   Assertions.assertThat(e.getMessage().startsWith("Failure executing: DELETE")); 
   Assertions.assertThat(e.getMessage().contains("Message: MSG")); 
   Assertions.assertThat(not(e.getMessage().contains("Received status"))); `

**Comment by rohanKanojia** [comment]
Yeah, looks right :+1:

**Comment by KamalSinghKhanna** [comment]
Hi @rohanKanojia  in order to make tests I tried to run mvn clean install but it is showing error.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project kubernetes-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/kamal/Desktop/Java-project/kubernetes-client/kubernetes-client/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :kubernetes-client
`

how to fix it?

**Comment by KamalSinghKhanna** [comment]
Hi @rohanKanojia in order to make tests I tried to run mvn clean install but it is showing error.


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project kubernetes-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/kamal/Desktop/Java-project/kubernetes-client/kubernetes-client/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :kubernetes-client

how to fix it?
