### ISSUE TITLE
Builders do not preserve additionalProperties

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3570]
When using a builder and you use a withXXX to associate another object - under the covers the a copy is made via a constructor that omits the additional properties.

**Comment by manusa** [comment]
Is this something that needs to be fixed here or in Sundrio?

A reproducer example, or ignored test would be useful.

**Comment by shawkins** [comment]
> Is this something that needs to be fixed here or in Sundrio?

I think here.  There's no constructor nor setter for the building logic to use to convey the additionalProperties.  If I modify Pod.java to have a setter, the the fluent / builder is updated appropriately.

**Comment by shawkins** [comment]
@manusa @iocanel or do you want an upstream issue about understanding the existing setAdditionalProperty?  A possible issue with that is that it's not symmetric - there's only getAdditionalProperties,

**Comment by manusa** [comment]
> A possible issue with that is that it's not symmetric - there's only getAdditionalProperties

I think jsonschema2pojo is in charge of generating the additionalProperties field and related methods (property setter, and getter).

I'm not sure if this can  be tweaked to be able to add a normal setter too and prevent the problem. But if there's no option, it seems like a hard problem to tackle then.

And I think the issue is similar for the constructor.
