### ISSUE TITLE
Integration tests will use defaults from the 4.x client

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3640]
The integration tests are using Arquillian logic based upon a 4.x uber jar.  The logic to construct a client will construct the Config off of the Config from the 4.x client, meaning that defaults from that version will be used instead - in particular I noticed that during integration tests the watch ping interval is 1 second rather than 30 seconds.

**Comment by rohanKanojia** [comment]
I think we need to refactor integration tests out of arquillian since they make us dependent on Junit4 and require cluster level access (they create a new namespace on each execution). This also prevents us from testing on OpenShift 4.x clusters since it's not possible to run OpenShift 4 on Github Action VM.

**Comment by manusa** [comment]
Just to put things clear:
- Arquillian has a dependency towards Kubernetes Client 4.x
- The fact that we are depending on Arquillian to bootstrap our cluster scenarios, makes us consume the Config from the Kubernetes Client 4.x version provided by Arquillian.

I don't really think that Arquillian is adding too much value right now, it could be easily replaced by a JUnit Extension that created and deleted a namespace.

**Comment by shawkins** [comment]
Closing via #4008

**Comment by manusa** [comment]
> Closing via #4008

:pray: thx!
