### ISSUE TITLE
What version of Kubernetes is supported by this client library ?

### ISSUE THREAD

**Issue by ramukima** [fabric8io/kubernetes-client#374]
Is it possible to mark the release tags with corresponding kubernetes version that the library has been tested on ? Alternatively, list the supported versions ?

**Comment by iocanel** [comment]
Recently, @jimmidyson added support for exposing the client version through the api. What was actually done is exposing the ${project.version} from the maven.

I am wondering if we could add something similar like the server version range for Kubernetes and Open shift. 

Then we could expose them both at runtime (like docker version, kubectl version etc).

But more importantly advertise them in our *release notes*.

@rawlingsj, @jstrachan: Do we know of any maven plugin that we can hook to our release process in order to generate and public release notes (in github) out of maven properties? If not do u think we could it using our release.groovy magic?

**Comment by rohanKanojia** [comment]
@ramukima : We have added this compatibility matrix in our README which shows which versions of kubernetes are supported. Right now kuberntes-client supports Kubernetes 1.12.2. Are we good to close this issue?
