### ISSUE TITLE
Version class after module split

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3831]
### Is your task related to a problem? Please describe

Do we want just a single version class or multiple version classes - one for the api, and one for the impl?

### Describe the solution you'd like

I don't have a strong preference, but if the expectation is for the impl to provide its version, then it should do so in a way that doesn't require referencing a class in the impl - for example Client.getVerion

**Comment by manusa** [comment]
I think we first need to clarify how is this Version class used.

From what I've gathered, this is used to set the default User Agent:
https://github.com/fabric8io/kubernetes-client/blob/755d8aa4d584e1709865dda6b2e6340765a4faf6/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L129

And in the new Java generator to print the version of the client (this one shouldn't really be a problem because the generator should only depend on the API + I don't know what's the added value of exposing this --> maybe better expose the version of the CLI and dig from there)
https://github.com/fabric8io/kubernetes-client/blob/1d7d869681faafe166e5581bcde0f928499ef765/java-generator/cli/src/main/java/io/fabric8/java/generator/cli/KubernetesClientVersionProvider.java#L24

For the User Agent case, I understand that the need is only one, either the IMPL or the API, but not both.

**Comment by shawkins** [comment]
> I think we first need to clarify how is this Version class used.

As long as we are only worried about our internal usage that simplifies things. 

The simplest option for now then is to just remove / repackage the Version class from -client and not worry about a public way of exposing the potential differentiation.
