### ISSUE TITLE
The client should lazily load / create the configuration

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#4085]
### Is your enhancement related to a problem? Please describe

Currently, when we instantiate the client, we create behind the scenes an instance of the `Configuration` object. This can be problematic in cases where AOT is involved as some configuration options like paths, may be invalid during compilation.

This is infact an issue in quarkus: https://github.com/quarkusio/quarkus/issues/23681

Besides that it somehow feels wrong not to be able to even instantiate the client if some of the paths, etc are invalid.

### Describe the solution you'd like

I think that the client should not be instantiated using a `Configuration` instance  but a `Provider<Configuration>` instead.

The actual `Configuration` should only be obtained from the provider on demand.

**Comment by johurul000** [comment]
@iocanel I will try this

**Comment by shawkins** [comment]
https://github.com/quarkusio/quarkus/issues/12417#issuecomment-1105886234 - looks related as well.

@iocanel @manusa @johurul000 based upon the original quarkus issue there are several problems.

1. what, if anything, is leaking into the build time configuration from autoConfigure:

https://github.com/quarkusio/quarkus/blob/a83a0a0078f50ef16acc1def1be59c1e1cb5d480/extensions/kubernetes-client/runtime-internal/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesClientUtils.java#L18

2. As the stacktrace on the issue highlights, quarkus is creating the full client instance at build time, which includes the HttpClient.  This is because by default the DefaultKubernetesClient constructor (or the same thing would happen now if you call KubernetesClientBuilder.build()) will create the client proactively.  From a KubernetesClient project perspective that seems entirely reasonable.  

3. There is also a potential for an SSLUtils.isHttpsAvailable that can be called automatically the Config logic - but it requires a master url without a protocol, so it's not that big of an issue.

One conclusion is that If we can't do 1 at build time, then we obviously can't do 2, so quarkus would need to change their logic to let the config and client construction be a runtime responsibility instead.

**Comment by geoand** [comment]
I am pretty sure the client is used internally when deploying to k8s / openshift

**Comment by shawkins** [comment]
> Are we sure that this pre-built client is the one later on used in: [KubernetesClientProducer](https://github.com/quarkusio/quarkus/blob/ada44ba375b4f0b8d2ae3c0b4bddc627de2138ae/extensions/kubernetes-client/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesClientProducer.java#L13)

I was just assuming from the quarkus issue that the build-time one was also used for the runtime, but you are correct the the producer classes should provide different instances presumably those are for runtime.

So the issue here really comes down to the client constructed for build time operations, such as deployment, is picking up properties that @iocanel intended for runtime.  I vote for closing this issue and continuing the discussion on the quarkus issue.
