### ISSUE TITLE
Support subresources, e.g. scale, deploymentrollback, etc

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/kubernetes-client#417]
Certain operations are applicable via subresources rather than updating the resource. We need a general way to support this as it's important for authorization policies that allow updating via subresources but not the resource itself.

**Comment by xguerin** [comment]
Has there been any updates on that topic?

**Comment by XciD** [comment]
Any update ?

**Comment by rohanKanojia** [comment]
@XciD : Unfortunately I haven't been able to find time to fix this. Could you please create a PR to support these if you have bandwidth?

**Comment by jglick** [comment]
Found this by noticing that the `scale` method, despite seeming similar to the `kubectl` command, requires `patch` rather than the more limited `put/scale` in RBAC, so is not using the [designated API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#replace-scale-statefulset-v1-apps).

**Comment by rohanKanojia** [comment]
@jglick : Thanks for pointing this out. I also think we should use designated api. So for starting what resources shall we consider adding support in model/DSL? I have these in mind:

- DeploymentRollback
- Scale
- DeleteOptions
- CreateOptions
- GetOptions
- ListOptions
- PatchOptions
