### ISSUE TITLE
The close method of defaultkubernetesclient returned by calling the defaultkubernetesclient innamespace method will close the original httpclient

### ISSUE THREAD

**Issue by walnut-tom** [fabric8io/kubernetes-client#4177]
### Is your enhancement related to a problem? Please describe

NamespacedKubernetesClient kubernetesClient = new DefaultKubernetesClient(masterUrl);

NamespacedKubernetesClient client = kubernetesClient.inNamespace("default");
.....
**client.close();**

kubernetesClient.apps().deployments().withName(name).get();

will cause a **KubernetesClientException**  Exception 

### Describe the solution you'd like
class DefaultKubernetesClient ... {
  
   @Override
    public NamespacedKubernetesClient inNamespace(String name) {
      io.fabric8.kubernetes.client.Config updated =
          new io.fabric8.kubernetes.client.ConfigBuilder(getConfiguration())
              .withNamespace(name)
              .build();
      return new PooledNamespacedKubernetesClient(newState(updated));
    }

 private static class PooledNamespacedKubernetesClient extends DefaultKubernetesClient {
   
    public PooledNamespacedKubernetesClient(ClientContext clientContext) {
      super(clientContext);
    }

      @Override
      public void close() {
        // do nothing
      }
  }
}

**Comment by shawkins** [comment]
> Do you still need to close the KubernetesClient after using it?

Yes

>  If necessary, what is the significance of using okhttpclient (ConnectionPool) in the lower layer? 

Closing the KubernetesClient closes the okhttpclient resources.

> And the KubernetesClient created through the inNamespace call closes resources that do not belong to itself.

It should not be understood as having separate resources.  Only new DefaultKubernetesClient(masterUrl) is allocating the underlying resources.

> If you do not need to close it, what scenarios are used to implement the autoclosable interface?

Mostly for what is shown in examples that is a standalone usage of the client:

try (KubernetesClient client = new DefaultKubernetesClient(masterUrl)) {
  ...
}

In other scenarios, for example where the client is injected, close does not need to be directly called.

**Comment by shawkins** [comment]
Your view is that the DefaultKubernetesClient is a KubernetesClient pool - that has never been the design / implementation.  Regardless of the methods you call it is logically a single client instance surrounding a single http client.  

If you feel strongly about it behaving like a pool, you could advocate for this change via a PR.

**Comment by manusa** [comment]
Some notes, especially regarding the Kubernetes Client 6.0 release.

We start from a KubernetesClient|NamespacedKubernetesClient|OpenShiftClient|XxxxKubernetesClient.

When the client is built or instantiated (createNewClient), a new underlying, AutoCloseable, HttpClient (Fabric8) instance is created.

The contract for the implementations (OkHttp, Jdk, Jetty, and so on), establishes that a single pool of resources is created and shared amongst all of the HttpClient (Fabric8) instances.

By closing **any** of the KubernetesClient instances, ---> (Fabric8) HttpClient instances, the pool of resources should be released.

So, yes a KubernetesClient should be closed whenever the application ends, but you don't need to keep track of each instance, since the resources should be shared among all of them.

**Comment by walnut-tom** [comment]
I will remove all **try (NamespacedKubernetesClient client = ...)** block
