### ISSUE TITLE
Throw an exception when a resource cannot be deserialised instead of passing `null` downstream

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#4206]
### Is your enhancement related to a problem? Please describe

It sometimes happen that a resource cannot be deserialised but when that happens the downstream code gets a `null` object thus resulting in an NPE further downstream where the cause might not be obvious. Not actually sure if this behavior is present in JVM mode but this is definitely an issue when running the client in a native binary.

### Describe the solution you'd like

An exception should be thrown allowing to identify which resource couldn't be deserialised (and any exception that might help explain why along the way).

**Comment by manusa** [comment]
@shawkins addresses this issue in #4263 where the `KubernetesDeserializer` is modified so that invalid resources are deserialized into `GenericKubernetesResource` regardless of the missing  GVK **required** fields.

In his PR, the check for a non-null key is removed:

https://github.com/fabric8io/kubernetes-client/blob/a98fda9c876194adfa3bce520cb53446fa1f8f1e/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java#L119

This is a valid scenario for [IngressController](https://github.com/fabric8io/kubernetes-client/blob/8c9b3a5bad21cfec327511ea2c6a1eb4bd32cdf8/kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/IngressController.java) or [NamedExtension](https://github.com/fabric8io/kubernetes-client/blob/18fa70ef95b7f60dba6b30ab58fb8cc1e05f10d8/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/NamedExtension.java) (and many others), that have nested fields with a HasMetadata type.

These classes have nested fields with `HasMetadata` types (not OK) that will be handled by the `KubernetesDeserializer`:

https://github.com/fabric8io/kubernetes-client/blob/296ec4fea3e4369c8a248220fb9abcad969ce6d3/kubernetes-model-generator/openshift-model-operator/src/generated/java/io/fabric8/openshift/api/model/operator/v1/IngressControllerSpec.java#L109

https://github.com/fabric8io/kubernetes-client/blob/18fa70ef95b7f60dba6b30ab58fb8cc1e05f10d8/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/NamedExtension.java#L40

Since the values of this fields won't contain the GVK coordinates, they won't be deserialized (return null in `KubernetesDeserializer`)

The proper fix would be to address the Go-Java mappings so that runtime.RawExtension is mapped to something else, `HasMetadata` should be reserved for valid Kubernetes API resources.

https://github.com/fabric8io/kubernetes-client/blob/296ec4fea3e4369c8a248220fb9abcad969ce6d3/kubernetes-model-generator/pkg/schemagen/generate.go#L180-L181

However, this might break the current model and fluent builders.

---

#4263 Has implications that might confuse users, any YAML file will now be deserialized into a GenericKubernetesResource.

This might also be against the expected behavior described by Chris:

> An exception should be thrown allowing to identify which resource couldn't be deserialised (and any exception that might help explain why along the way)

From JKube's perspective, we'd need to check if the new proposed behavior would break our current apply operations.

**Comment by metacosm** [comment]
Indeed, the proposed solution of returning a `GenericKubernetesResource` might not be that helpful to diagnose any potential issue…
