### ISSUE TITLE
"description" is a protected keyword and is ignored on generation, can we somehow allow this for the content

### ISSUE THREAD

**Issue by mteubner** [fabric8io/kubernetes-client#4546]
### Component java-generator ignores "description" field definition in content

I don't understand how to use CustomRessourceDefinitions containing "description" as field in the content. Due to the fact that it is part of the IGNORED_FIELDS in JObject.

I get that "description" is a protected keyword somehow to actually also describe an object in open API and that is therefore put to javadoccomments, but what if the Object itself has an field named description.

When I try generating an object with
description:
   type: string

It will not appear in the generated code.

### Describe the solution you'd like

I actually don't have an idea how to implement it, but I would like to have the possibility to use description also as content, not only as interface explaination.

### Describe alternatives you've considered

Currently I don't use the generated code, but generated it once and added the missing fields. This should not be the prefered way.

### Additional context

Maybe there is some hidden proerty to the generator to use it differently, but I did not find any code in the project that would let me think I can use "description" as ones object field.

**Comment by andreaTP** [comment]
Hi @mteubner , would you be able to provide a minimal reproduction for this issue?

The `description` field is already explicitly handled so that it will end up in the relevant `JsonPropertyDescription` annotation and in the JavaDoc:

https://github.com/fabric8io/kubernetes-client/blob/2ee77a00f40c8a2cf43350e1e377b843cac45a46/java-generator/core/src/test/resources/keycloak-crd.yml#L53

https://github.com/fabric8io/kubernetes-client/blob/master/java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testKeycloakCrd.approved.txt#L21

https://github.com/fabric8io/kubernetes-client/blob/2ee77a00f40c8a2cf43350e1e377b843cac45a46/java-generator/core/src/test/resources/io/fabric8/java/generator/approvals/ApprovalTest.generate_withValidCrd_shouldGeneratePojos.testKeycloakCrd.approved.txt#L17-L19

If this is not happening can you share the faulty CRD?

**Comment by andreaTP** [comment]
Unfortunately no, there is no available workaround with the current implementation.

Thanks a lot for sharing the example, the `IGNORED_FIELDS` might be a shortcoming used in the first prototype, I would need to check the consequences of completely removing it ...

But this is a legit bug and I will look into it, thanks a lot for filing it 👍
