### ISSUE TITLE
Support for Seamlessly Sharing Informers with Same Configuration

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#5097]
Currently in Java Operator SDK we think how to optimize connections, especially if multiple reconcilers are watching the same resource(s) with informers. The typical use case is that a reconciler manages a custom resource, and the other reconciler reconciles that. In this case typically even the label selectors and other configurations are shared, so the underlying informer could be shared to. 

One way to solve this would be on JOSDK level, to handle a pool of informers and making sure we create only one with for a specific configuration.

On the other hand as we discussed briefly offline, this could be approached also on level of the client, thus have an option to provide  informer factory that will produce the informers, and the provided informers could share the connection / watch or the whole informer.

**Comment by manusa** [comment]
An intermediate SharedInformer pool could be created in order to create or retrieve informers that already exist for a given query. Users could then be able to add new handles to the existent informers.

**Comment by shawkins** [comment]
I'm a little suspicious of trying to implement implicit behavior under the existing calls - ensuring the same behavior regardless of whether you are dealing with a new or existing informer will be problematic.

It's less risky to start with supporting projection - that is have a root informer that you can project subinformers off of based upon additional predicates.  I get that this may not closely match the JOSDK usage scenario though.

> On the other hand as we discussed briefly offline, this could be approached also on level of the client, thus have an option to provide informer factory that will produce the informers, and the provided informers could share the connection / watch or the whole informer.

The existing SharedInformerFactory is supposed to operate like this, but has the following issues:
- it's not very explicit on it's own lifecycle / sharing scope - it's created for each call to KubernetesClient.informers returned a new instance.
- creating / returning specialized informers was problematic, so that logic was mostly deprecated.  withName and inNamespace as still exposed, but they are actually setting those fields on the existing factory and apply only to informers registered/started after that point.

We can of course revisit the SharedInformerFactory to enable explicit sharing.
