### ISSUE TITLE
should we have a pods().withSelector(LabelSelector)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#511]
we have various withLabel() methods like `withLabels(Map<String,String>)`, `withLabel(String, String)` but should we have a withSelector(LabelSelector) which then wraps up iterating through the LabelSelector turning it into matchLabels etc?

**Comment by jstrachan** [comment]
if its any help - here's the code I hacked together to try convert a LabelSelector into the various filters
https://github.com/jstrachan/fabric8-maven-plugin/blob/8c861850c329930586ec8328c63b2a1826bf0354/plugin/src/main/java/io/fabric8/maven/plugin/AbstractTailLogMojo.java#L327-L327

**Comment by jbguerraz** [comment]
`withSelector("partition in (customerA, customerB),environment!=qa")` would be great.
That way we could use both "Equality-based requirement" and"Set-based requirement" (CF http://kubernetes.io/docs/user-guide/labels/#label-selectors)

**Comment by jstrachan** [comment]
though right now you could do that via:
```java
kubernetesClient.pods().withLabelIn("partition", "customerA", "customerB").withLabelNotIn("environment", "qa");
```
which I think is about the same thing and a little more typesafe?

**Comment by jimmidyson** [comment]
Yes we prefer the label selector builder methods rather than a simple string.

**Comment by jbguerraz** [comment]
I got the way you see it :)
Fabric8.io usage of the that k8s API could make that useless but if somehow you have to ask a user to input a selector then this user could actually enter a thing like that `"partition in (customerA, customerB),environment!=qa"`; having to parse it in order to use such a builder makes things.. painful.
Considering at the end it's actually a string value sent thru HTTP (e.g: https://HOST/api/v1/namespaces/default/pods?labelSelector=environment%21%3Dqa%2Cpartition+in+%28customerA%2CcustomerB%29) it's actually a lot of processing for moving a string into *objects* and then back again into a string.

**Comment by jstrachan** [comment]
@jbguerraz having a helper function to parse LabelSelector from a String and go back to a String again sounds good to me! Fancy submitting a PR?
