### ISSUE TITLE
Clashing package names in trigger model dependencies

### ISSUE THREAD

**Issue by ggallen** [fabric8io/kubernetes-client#5113]
### Describe the bug

I am seeing this warning when compiling my application:
```
WARNING] [io.quarkus.arc.deployment.SplitPackageProcessor] Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
 "io.fabric8.tekton.triggers.internal.knative.pkg.apis.duck.v1" found in [io.fabric8:tekton-model-triggers-v1alpha1::jar, io.fabric8:tekton-model-triggers-v1beta1::jar]
 "io.fabric8.tekton.triggers.internal.knative.pkg.apis" found in [io.fabric8:tekton-model-triggers-v1alpha1::jar, io.fabric8:tekton-model-triggers-v1beta1::jar]
```
This looks like maybe I am pulling in two dependencies (v1alpha1 and v1beta1), and I should only be pulling in one?

This seems to be similar to https://github.com/fabric8io/kubernetes-client/issues/5000.

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Compile a Quarkus application that uses triggers.

### Expected behavior

No warning is generated.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by rohanKanojia** [comment]
Instead of generating `io.fabric8.tekton.triggers.internal.knative.pkg.apis.duck` packages in both v1alpha1 and v1beta1 trigger model generators, maybe we should only generate it in v1alpha1 and make v1beta1 depend on v1alpha1.

Since these structs are originally coming from knative model, we can also make both of these models depend on knative-model and use these structs from there.
