### ISSUE TITLE
Include all httpclient artifacts in the BOM

### ISSUE THREAD

**Issue by mattnelson** [fabric8io/kubernetes-client#5168]
### Is your enhancement related to a problem? Please describe

The `kubernetes-client-bom` does not include entries for the jdk/jetty http client implementations. When using either of them additional dependency management is needed.

dependency management
```diff
<properties>
  <k8s.client.version>6.6.2</k8s.client.version>
</properties>
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client-bom</artifactId>
      <version>${k8s.client.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
+  <dependency> <!-- this GAV should be managed in the BOM -->
+    <groupId>io.fabric8</groupId>
+    <artifactId>kubernetes-httpclient-jdk</artifactId>
+    <version>${k8s.client.version}</version>
+  </dependency>
  </dependencies>
</dependencyManagement>
```

### Describe the solution you'd like

Add `kubernetes-httpclient-jdk` and `kubernetes-httpclient-jetty` to `kubernetes-client-bom`

### Describe alternatives you've considered

Continue managing explicitly.

### Additional context

The vertx client is managed in the bom

**Comment by manusa** [comment]
Indeed, the 2 mentioned HttpClient modules are missing from https://repo1.maven.org/maven2/io/fabric8/kubernetes-client-bom/6.6.2/kubernetes-client-bom-6.6.2.pom

These modules require Java11+, so that's why they're excluded from the Java8 bundles.

I'll try to find a workaround to include these modules only for the BOM packaging.
