### ISSUE TITLE
ProjectRequestIT timeout

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5185]
One of the more common flaky integration tests of late is a timeout [ProjectRequestIT.create:53 » Timeout](https://github.com/fabric8io/kubernetes-client/actions/runs/5111624056/jobs/9189106962#step:6:493)

**Comment by manusa** [comment]
This one relies on the cluster creating the requested project. I'm not sure that there's an easy way to make it more reliable other than adding some sort of automatic retry.

Also, not sure that this is due to a late informer start (shouldn't be), maybe starting the informer before the requesting the project and getting the promise later can help (but shouldn't).

https://github.com/fabric8io/kubernetes-client/blob/1e425168f3c79c3cf30416e3b4cb38f64d4cdcad/kubernetes-itests/src/test/java/io/fabric8/openshift/ProjectRequestIT.java#L46-L53

**Comment by shawkins** [comment]
> Also, not sure that this is due to a late informer start (shouldn't be), maybe starting the informer before the requesting the project and getting the promise later can help (but shouldn't).

The concern is that since a project is a derived resource over a namespace that watches may not work 100% correctly.  Perhaps we should confirm this by not throwing the timeout exception, but allowing the following get to proceed.  If the test starts passing then we'll know that the watch isn't reliable, if it keeps failing then the timeout needs increased.
