### ISSUE TITLE
List items should implement the equals method

### ISSUE THREAD

**Issue by ggallen** [fabric8io/kubernetes-client#5266]
### Describe the bug

List objects should implement `equals` so that `List.contains()` works as expected.

For example, take a `ClusterRoleBinding` object, which contains a list of `Subjects`. If I create a `Subject` object duplicating a subject already in the `ClusterRoleBinding`, and then call `ClusterRoleBindinger.getSubjects().contains(subject)`, `false` is returned.  

It should return `true`.

I can see that in the `Subject` source file, the `equals` method is not defined.
`kubernetes-model-generator/kubernetes-model-rbac/src/generated/java/io/fabric8/kubernetes/api/model/rbac/Subject.java`

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

1. Create a subject, duplicating one that is already contained in a `ClusterRoleBinding`.
2. Call `ClusterRoleBinding.getSubjects().contains(subject)`. It will return false.

### Expected behavior

In this case, `ClusterRoleBinding.getSubjects().contains(subject)` should return true.

### Runtime

Kubernetes (vanilla), OpenShift, minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Additional context

This may be considered a feature request, but I filed it as a bug as I think the expected behavior is for `equals` to be implemented.

**Comment by shawkins** [comment]
> List objects should implement equals so that List.contains() works as expected.

The do have an equality method - https://github.com/fabric8io/kubernetes-client/blob/2e804c079b8c3cc14eecd057df1d1b55616de3cb/kubernetes-model-generator/kubernetes-model-rbac/src/generated/java/io/fabric8/kubernetes/api/model/rbac/Subject.java#L41 

However that is full structural equality - it is probably not passing passing because the server server is changing the Subject you are retrieving from the server - making the namespace explicit, adding addtionalProperties, etc. - such that it's not fully the same.

What you are looking for is probably some semantic equality - maybe just check by name or only the fields of the Subject you actually care about.

**Comment by ggallen** [comment]
@shawkins, you are correct. I missed that annotation and had never heard of it.  I learned something.  Thanks.

And I also do want semantic equality. It's just what I expected, and I think most users would. The `Subject` in a `ClusterRoleBinding` only has three fields. It seemed natural to me that the equality check for `List.contains()` would only use those fields.

**Comment by ggallen** [comment]
@shawkins, so is the only way to add a `Subject` to a `ClusterRoleBinding` without getting duplicates require manually checking the list of subjects already there first?  Is there anything more elegant?

**Comment by ggallen** [comment]
> Which field is causing a problem with equality? Is the server populating the namespace?

This was a great question. It was `ApiVersion`, which I was setting.  It's not needed, and once I removed it the call to `ClusterRoleBinding.getEvents().contains(subject)` works as expected.

Thanks for the help!
