### ISSUE TITLE
Implement portforward

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#534]
We already use it in a handful of places, using the binaries. It would be awesome if the client supported it.

**Comment by iocanel** [comment]
@rcernich, @jwendell, @alesj, @spolti  have already done a great job implementing something like this, here: https://github.com/arquillian/arquillian-cube/blob/master/openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwarder.java

I am pretty sure, that it wouldn't be that hard to port that code to use okhttp3 and the rest of the facilities we use in the `kubernetes-client`.

Guys would you be interested / have the cycles to port the port forwarding logic directly into the client?

**Comment by rcernich** [comment]
@iocanel I couldn't figure out how to make this work with okhttp.  I needed access to both the request and response streams so I could transfer between two connections, i.e. I couldn't figure out how to handle long running requests.  Also, the k8s spdy implementation is not complete, so we needed to add some workarounds to get it to work with undertow.  Specifically, it doesn't send window updates, so the client would eventually stop sending data once it exhausted the send window.

**Comment by iocanel** [comment]
@rcernich: I have no clue on how portforward works internally, so I can't really understand the challenges :-)

Let me have a look...

**Comment by rcernich** [comment]
@iocanel, it looked like okhttp was setup to send a request, then receive a response.  For port forwarding, you need to keep the request and response streams open simultaneously, since the application protocol may be something other than simple http requests, e.g. eap management, jdbc, jms, etc.

**Comment by kolleroot** [comment]
Hi there, are there any updates regarding this issue?
It would be really great to have this feature in the library, because a hack with `kubectl port-forward` would be very messy.

I think, that #417 is also relevant to this issue, because in the kubectl command they also use the sub resource construct to access the port forward resource (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/portforward.go#L194-L198). But I think it just appends `/portforward` to the pod resource url. So #417 is not a requirement but would generalize the accessing of sub resources.
