### ISSUE TITLE
mockwebserver does not return set expected responses

### ISSUE THREAD

**Issue by sandy-sandeeep** [fabric8io/kubernetes-client#5422]
### Describe the bug

server.expect()
                .post()
                .withPath("somepath")
                .andReturn("400", "message")
                .once();

is returning 400 and the message that is set 

server.expect()
                .post()
                .withPath("somepath")
                .andReturn("420", "message")
                .once();

is also behaving the way it is expected.

But when I try to add expectations for 429, 500 and 100. I am not getting the expected response instead getting 404 with message : Not Found.

I have tested this in the same test that is working for above to 400 and 420... No logic is changed but behavior is changing for other error codes

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

In any of your existing functional test for post on mockwebserver change the return code to 429 and see if you are getting the expected rsponse if you run the test.

### Expected behavior

you should receive the mentioned error code and message that is set in the expectation

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Additional context

I am using fabric8.version 6.7.0 for kubernetes-client kubernetes-server-mock also 6.7.0

**Comment by manusa** [comment]
Could you please provide the expectation code fragment you're using?

Have you checked the logs to see if there might be some nuances (e.g. query params) in the URL that you're mocking?

**Comment by sandy-sandeeep** [comment]
its just a simple post call with no fancy checks. The expectation is exactly the same as the one I shared for example

**Comment by sandy-sandeeep** [comment]
server.expect()
                .any()
                .withPath("/apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications")
                .andReturn(responseCode, responseBody)
                .once();

**Comment by manusa** [comment]
OK, once I've examined your specific use-case, I believe you're being victim of our automatic retry handler.
Since you're mocking the expectation once and you have the default request retry limits and intervals, the client is automatically retrying upon the received non-successful HTTP status codes.

I'm sure that in your logs you might be seeing the actual expected response:

```
INFO: MockWebServer[52865] received request: POST /apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications HTTP/1.1 and responded: HTTP/1.1 429 Client Error
```

followed by:

```
INFO: MockWebServer[52865] received request: POST /apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications HTTP/1.1 and responded: HTTP/1.1 404 Client Error
```

Which is what the client eventually returns.

To properly test this you can do the following in your test:

```java
client.getConfiguration().setRequestRetryBackoffLimit(0);
```

which basically disables the automatic retries.

You could also set the expectation to `.always()` but that would make the test run for a long time (which is probably something you don't want).

In production you can leverage the following configurations (see README.md):

- `kubernetes.request.retry.backoffLimit` / `KUBERNETES_REQUEST_RETRY_BACKOFFLIMIT`
- `kubernetes.request.retry.backoffInterval` / `KUBERNETES_REQUEST_RETRY_BACKOFFINTERVAL`
