### ISSUE TITLE
[extensions/istio] : LoadBalancerSettingsSimpleLB  can`t found the LEAST_REQUEST

### ISSUE THREAD

**Issue by frankywen** [fabric8io/kubernetes-client#5582]
### Is your enhancement related to a problem? Please describe

in LoadBalancerSettingsSimpleLB  can`t found the LEAST_REQUEST

### Describe the solution you'd like

add LEAST_REQUEST to LoadBalancerSettingsSimpleLB class

**Comment by rohanKanojia** [comment]
Related to https://github.com/fabric8io/kubernetes-client/issues/5182 
The java model for Istio extension seems to be a bit outdated. We need to update it as per latest releases.

If you have time, please help us in updating the model.

**Comment by professorabhay** [comment]
Hey, @rohanKanojia ! I would like to work on it with some guidance. And help to update as per latest release.

**Comment by rohanKanojia** [comment]
You would need to update the dependencies listed in istio generator to latest available versions:

https://github.com/fabric8io/kubernetes-client/blob/b8d5ce45d9583d5e7d9a4aa2718d45eb05eae89b/extensions/istio/generator-v1beta1/go.mod#L6-L14

Then run `go mod tidy` and then `make` afterward. There are going to be some errors during `make` since we haven't upgraded since a long time.

**Comment by professorabhay** [comment]
Ok @rohanKanojia ! Got everything. 
I'm starting to work on it and raise the PR as soon as possible. And will let you know if I need any help within it. You can assign it to me 🙂

**Comment by andreaTP** [comment]
@manusa should we move the extensions in this repo to use the `java-generator` ?
Following your example: https://github.com/fabric8io/kubernetes-client/compare/main...manusa:kubernetes-client:extension/kubevirt

I have quickly attempted to generate the Istio Client and everything seems good apart from a couple of rough edges in `sundrio`. thoughts?

**Comment by mailingfeng** [comment]
same issue, looking forward to the new version

**Comment by rohanKanojia** [comment]
This issue should be fixed by Istio model upgrade PR https://github.com/fabric8io/kubernetes-client/pull/5903

I'm able to see LEAST_REQUEST in [LoadBalancerSettingsSimpleLB enum](https://github.com/rohanKanojia/kubernetes-client/blob/71024572ba1b260a2d1dea973c529db8bc3fd8a0/extensions/istio/model-v1beta1/src/generated/java/io/fabric8/istio/api/networking/v1beta1/LoadBalancerSettingsSimpleLB.java#L17)

**Comment by rohanKanojia** [comment]
@mailingfeng  @frankywen : Istio Extension should now be upgraded to Istio v1.21.0 . You should be able to try out the SNAPSHOT version after today's nightly build. Would be great if you could try it out and provide feedback.

In order to use `6.13-SNAPSHOT`, You need to add this to your project's `pom.xml` or `~/.m2/settings.xml`
```xml
      <repositories>
        <repository>
          <id>sonatype-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```

**Comment by mailingfeng** [comment]
Good Jod，nice~!
