### ISSUE TITLE
Upload file/dir to pod does not work in GKE

### ISSUE THREAD

**Issue by lior444** [fabric8io/kubernetes-client#5599]
### Describe the bug

Ever since our clusters were upgraded to a GKE version that works only with **containerd**, the upload method simply does not work. It does work on my local minikube, but not on GKE (1.25.10-gke.2700). 

Trying to debug this, I see that the upload process starts since I see a fragment of the file for less then a second in /tmp but it removed immediately after starting and the upload method returns **false**. 
Tried to play with kubernetes.upload.connection.timeout & kubernetes.upload.request.timeout but it doesn't help. 

Important to mention that my source is actually a different pod in the same cluster from which I initiate the kubernetes-client. From this pod the tests are executed and the API to deploy and trying to upload the file to the remote pod is ran. 
A simple kubectl cp command in the cluster does work. 

Any ides? 

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

1. Deploy a maven pod on a GKE cluster from which you can execute the kubernetes-client API and tests.
2. Try to deploy a different pod and upload a file to it using kubernetes-client code. 

### Expected behavior

The upload method will return false and the file/dir will not be copied. 

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

GKE

### Fabric8 Kubernetes Client Logs

```shell
No logs from the fabric8 are seen...
```

**Comment by manusa** [comment]
Might be the same root-cause as for #5527.

In any case, the same fix should likely apply.

**Comment by cr-liorholtzman** [comment]
@manusa hope so...
Though I don't see the "Read-only file system" in my case...

**Comment by manusa** [comment]
Well, I don't mean to say that the problem is a read-only file system or a `/tmp` directory with no write rights. But rather a `/tmp` directory that is **not** usable for whatever reason.

If in your case, the target directory is writeable, the same approach we can use to fix #5527 should also be valid for this.

**Comment by cr-liorholtzman** [comment]
@manusa I understand. To be honest, I'm not 100% sure that's the case because if it was, would kubectl cp work? 
I also tried kubectl cp directly to tmp and it **does work**.

**Comment by manusa** [comment]
> I also tried kubectl cp directly to tmp and it does work.

OK, this is weird then. Maybe @shawkins has some ideas about why this might be failing in our case and not for `kubectl`.

**Comment by shawkins** [comment]
@cr-liorholtzman @manusa It may take more debugging to see why it's returning false - with debug logging enabled you should see the reason false is returned.  

To workaround a kubernetes bug with websockets we added the logic that will first copy the file to the tmp location, then validate its size.  If for some reason your container is always reporting an unexpected size, then we'll consider the operation to have failed.

**Comment by shawkins** [comment]
The client uses slf4j, so you can configure it with whatever is bound as the logging implementation.

The relevant package / logging context here is io.fabric8.kubernetes.client.dsl.internal.uploadable - but you can go much higher up if you want to see more of what is happening.

**Comment by cr-liorholtzman** [comment]
@shawkins So I executed the test with debug and below are the logs. From what I can understand it's either that the webSocket is closed prematurely, or maybe fabric8 fails to transfer the file from /tmp to the destination folder (not sure if the validation is before/after the the pod

`12:38:23  2023-11-21 10:38:23:542 [fullIntegrationTest-3] INFO  c.c.d.s.SpringBootBaseContainerService.waitTillUp:53 - Container XXXX is UP
12:38:23  2023-11-21 10:38:23:543 [fullIntegrationTest-3] INFO  c.c.d.a.i.IntegrationTests.fullIntegrationTest:134 - XXXX is up
12:38:23  2023-11-21 10:38:23:543 [fullIntegrationTest-3] INFO  c.c.d.a.u.ContainerHelper.uploadFolderToPod:152 - Uploading dir from : /XXXXX/20220227
12:38:23  2023-11-21 10:38:23:603 [fullIntegrationTest-3] DEBUG i.f.k.c.d.i.c.v.PodOperationsImpl.validateOrDefaultContainerId:350 - using first container XXXX in pod XXXX
12:38:24  2023-11-21 10:38:23:701 [OkHttp https://XXXX/...] DEBUG i.f.k.c.d.i.ExecWebSocketListener.handle:120 - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
12:38:24  2023-11-21 10:38:23:702 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.ExecWebSocketListener.onClose:373 - Exec Web Socket: On Close with code:[1000], due to: []
12:38:24  2023-11-21 10:38:23:740 [OkHttp Dispatcher] DEBUG i.f.k.c.d.i.AbstractWatchManager.startWatch:314 - Watching https://XXXXX/api/v1/namespaces/XXXX?allowWatchBookmarks=true&fieldSelector=metadata.name%3DcXXXXXX&resourceVersion=1245545873&timeoutSeconds=600&watch=true...
12:38:24  2023-11-21 10:38:23:741 [fullIntegrationTest-3] DEBUG i.f.k.c.d.i.c.v.PodOperationsImpl.validateOrDefaultContainerId:350 - using first container XXXXX
12:38:24  2023-11-21 10:38:23:802 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.WatcherWebSocketListener.onOpen:40 - WebSocket successfully opened
12:38:24  2023-11-21 10:38:23:803 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.AbstractWatchManager.close:323 - Force closing the watch
12:38:24  2023-11-21 10:38:23:803 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.AbstractWatchManager.closeRequest:160 - Closing the current watch
12:38:24  2023-11-21 10:38:23:804 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.AbstractWatchManager.close:323 - Force closing the watch
12:38:24  2023-11-21 10:38:23:805 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.AbstractWatchManager.closeEvent:199 - Ignoring duplicate firing of onClose event
12:38:24  2023-11-21 10:38:23:806 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.WatcherWebSocketListener.onClose:65 - WebSocket close received. code: 1000, reason: 
12:38:24  2023-11-21 10:38:23:806 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.AbstractWatchManager.scheduleReconnect:219 - Ignoring already closed/closing connection
12:38:24  2023-11-21 10:38:23:863 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.ExecWebSocketListener.handle:111 - exec message received 2 bytes on channel stdOut
12:38:24  2023-11-21 10:38:23:900 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.ExecWebSocketListener.handle:120 - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
12:38:24  2023-11-21 10:38:23:903 [OkHttp https://10.208.0.1/...] DEBUG i.f.k.c.d.i.ExecWebSocketListener.onClose:373 - Exec Web Socket: On Close with code:[1000], due to: []
12:38:24  2023-11-21 10:38:23:903 [fullIntegrationTest-3] DEBUG i.f.k.c.d.i.u.PodUpload.upload:123 - upload file size validation failed, expected 1869312, but was 0`

**Comment by cr-liorholtzman** [comment]
You mean simple running "wc -c < tmpfile" in the pod? The tmpfile is removed shortly after the upload starts, I can see if for just a fragile of second...

**Comment by shawkins** [comment]
> @shawkins You mean simply running "wc -c < tmpfile" in the pod? The tmpfile is removed shortly after the upload starts, I can see it for just a fragile of second...

I mean on any file to start just to validate that the appropriate size is seen.

**Comment by cr-liorholtzman** [comment]
@shawkins tested now. It works... 
The upload also works locally if I test it with minikube, it only fails on GKE.

**Comment by shawkins** [comment]
> tested now, wc -c works well...

Meaning that on boty GKE and minikube you get an appropriate value back for any given file?  If that's the case it would imply that we're not transferring anything successfully to GKE in the first place.
