### ISSUE TITLE
remove bouncycastle dependency for EC key support

### ISSUE THREAD

**Issue by coopstah13** [fabric8io/kubernetes-client#6008]
### Is your task related to a problem? Please describe

Newer version of BouncyCastle doesn't work with BCFIPS provider

### Describe the solution you'd like

Remove dependency on BouncyCastle and rely on JDK only. The dependency is only used for EC keys, but they are supported since at least JDK8.

### Describe alternatives you've considered

I have pinned the transitive bouncycastle dependency to an older version (1.68) in our repository as it seems to be the last one that doesn't have the problem.

**Comment by shawkins** [comment]
@coopstah13 do you have suggested changes for this? The test case that was added for bcfips does not work with just the jdk - it fails with "java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : version mismatch: (supported:     00, parsed:     01 ..."

**Comment by shawkins** [comment]
> We probable need to add a specific case for
[CertUtils#handleECKey](https://github.com/fabric8io/kubernetes-client/blob/2f11261da823bc858658b3218c6f913af36a5342/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L180) so that we don't require the usage of BouncyCastle libraries for Elastic keys.

Yes, I understand what could be done for eliptical curve keys, but nothing simple worked. Taking another look the best I could come up with was to borrow some code from vertx. I'll open a pr with that.

**Comment by martinwunderlich-celonis** [comment]
I've had the same issue and was to remove the Bouncycastle library after upgrading the fabric8 client from 6.13.1 to 7.0-SNAPSHOT (built locally). 
Does anyone have an idea when 7.0.0 will get released?

**Comment by manusa** [comment]
> Does anyone have an idea when 7.0.0 will get released?

End of September or October if everything goes well.

**Comment by martinwunderlich-celonis** [comment]
Hello @manusa , just out of curiosity, is the release for 7.0.0 on track? Thank you
