### ISSUE TITLE
Remove no longer maintained dependency com.github.mifmif:generex

### ISSUE THREAD

**Issue by stianst** [fabric8io/kubernetes-client#6052]
### Is your enhancement related to a problem? Please describe

Auditing health and licenses for dependencies of Keycloak Operator this dependency was detected. The last release of the dependency was [2016-10-30](https://central.sonatype.com/artifact/com.github.mifmif/generex/versions), and can be considered abandoned by its maintainers as there has not been any activity. There's even a rather old open issue asking if the [project is still alive](https://github.com/mifmif/Generex/issues/53), but no response in nearly 5 years.

generex also has a transitive [dependency on automaton that is more than 10 years old](https://central.sonatype.com/artifact/dk.brics.automaton/automaton/versions), with an open [request to update](https://github.com/mifmif/Generex/issues/61).

### Describe the solution you'd like

Remove the use of the dependency that is no longer actively maintained.

**Comment by manusa** [comment]
See https://github.com/fabric8io/kubernetes-client/pull/6053#discussion_r1642638155

> This is not going to generate a valid template instance

Why is this?

> - generating a random string can easily lead to errors
> - the random string cannot be tracked

The purpose of this method is really to process locally the templates as if they were being processed by the OpenShift cluster.

It really doesn't matter if the string can't be tracked or if the random string is invalid (maybe because the provided expression is wrong).
In the end, this would be the user's responsibility.

```yaml
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
```
https://docs.openshift.com/container-platform/4.15/openshift_images/using-templates.html#templates-writing_using-templates


What we want is to be able to support this.

From the [docs](https://docs.openshift.com/container-platform/4.15/rest_api/template_apis/template-template-openshift-io-v1.html) we can read the constraints for this expression:

> generate specifies the generator to be used to generate random string from an input value specified by From field. The result string is stored into Value field. If empty, no generator is being used, leaving the result Value untouched. Optional.
>
> The only supported generator is "expression", which accepts a "from" value in the form of a simple regular expression containing the range expression "[a-zA-Z0-9]", and the length expression "a{length}".
> 
> Examples:
>
> | from | value |
> |------|-------|
> "test[0-9]{1}x" | "test7x"
> "[0-1]{8}" | "01001100"
> "0x[A-F0-9]{4}" | "0xB3AF"
> "[a-zA-Z0-9]{8}" | "hW4yQU5i"


It seems that a simple library or maybe even rolling our own utility method should suffice to handle this.

**Comment by andreaTP** [comment]
Thanks for linking the detailed docs!

> rolling our own utility method should suffice to handle this

Looks easy enough, it's a fun distraction I take it :+1:

**Comment by manusa** [comment]
> Looks easy enough, it's a fun distraction I take it 👍

Thanks :raised_hands:  :raised_hands:  :raised_hands:
