### ISSUE TITLE
Get data from k8s pod from last read

### ISSUE THREAD

**Issue by akash-nx** [fabric8io/kubernetes-client#6112]
I want to read data from k8s pod either in form of logs or file. I want to read it after specific time interval but from last read point. Previous data should not be repeated . Currently, for pod logs I am using watchLog:
```
LogWatch logWatch =client.pods()
					.inNamespace(namespace)
					.withName(podName)
					.sinceSeconds(10).watchLog();
```
above code gives me all logs from the beginning every time.

Also, I am trying to read application specific log file as below:
```
try (InputStream is = client.pods()
				  .inNamespace(namespace)
				  .withName(podName)
				  .file("/app/logs/demo.log")
				  .read())  {
					String result = new BufferedReader(new InputStreamReader(is)).lines().collect(Collectors.joining("\n"));
					System.out.println("> "+result);
				}
```

same issue with reading file as well.

How can I get latest logs/data using fabric8 client?

**Comment by manusa** [comment]
> Currently, for pod logs I am using watchLog:

Code-wise everything looks OK.

Is the result the same if you perform a `getLog()` instead?

**Comment by akash-nx** [comment]
@manusa I tried getLog() but it gives all logs from the beginning. For the logWatch, I modified my code and its giving expected output. How can I achieve the same for file read from pod? Can I always read files from last read?

**Comment by manusa** [comment]
> @manusa I tried getLog() but it gives all logs from the beginning

Output for both should be the same.

Note that it's the Kubernetes API server who is computing the required output through the passed in query parameter `sinceSeconds` when the Fabric8 Kubernetes Client performs the request.

See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#read-log-pod-v1-core

> How can I achieve the same for file read from pod? Can I always read files from last read?

I'm not sure what you mean here(what does `last read` mean?).

Assuming you want to read a file incrementally, then you'll need to implement your own command and execute it using our pod exec methods.
Otherwise, there's no built-in way in the client to achieve what you say (or what I think you're saying).

**Comment by akash-nx** [comment]
Yes, I want to read a file incrementally. I will check for docker exec command or other alternatives. Thanks @manusa, appreciate your help.

**Comment by manusa** [comment]
Just to be clear, I was referring to the exec tools that the Fabric8 Kubernetes Client provides.

From the examples:

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java#L50-L55

So basically you need a command to output the command of the file from a given line or position (maybe cut, tail, etc.)

**Comment by akash-nx** [comment]
Thats great help @manusa , below command works for me:
`k exec -it --namespace demo-namespace demo-container sh -- tail -f logs/demo.log`
