### ISSUE TITLE
OpenShiftOAuthInterceptor#authorize does not close the http client that it is creating

### ISSUE THREAD

**Issue by adietish** [fabric8io/kubernetes-client#6317]
### Describe the bug

`OpenShiftOAuthInterceptor#authorize` creates a new `HttpClient` buit isn't closing it once it finished its proceedings

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

https://github.com/fabric8io/kubernetes-client/blob/0e4baf0772919433162420d31e6ca11284250862/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java#L87-L90
### Expected behavior

The httpclient should be closed when it's not used any more. This can be achieved with a try-with-resource clause

### Runtime

OpenShift

**Comment by manusa** [comment]
This is a derived client, it shouldn't need closing as the parent client will close the derived client's resources when closed.
Closing the derived client will cause even cause issues to the parent client, since its resources (Thread pools and so on) will be closed and no longer available.

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/HttpClient.java#L133

Maybe this should be better documented.

/cc @shawkins

**Comment by shawkins** [comment]
This is the convention we inherited from okhttp and our code implicitly relies on it. There's not great alternatives, so whatever docs make it clearer would be good. 

Treating derived clients as separate will lead to a lot more overhead in creating http clients. We could entertain treading derived close as a no-op, but that will mean we'll need to add another method for "root close".

**Comment by adietish** [comment]
ok, my aim was to fix a possible memory leak. If that's not the case, I'd add a comment in the code and consider this issue moot. Agree?
