### ISSUE TITLE
Invalid CRD with when no string default value is used

### ISSUE THREAD

**Issue by mfvitale** [fabric8io/kubernetes-client#6654]
### Describe the bug

With the generator v2 the default are not working as expected. If you define for example

```java
@Default(defaultValue = "60000")
private long flushMs = 60000L;
```

the generated crd will put the default value as a string causing the crd to not be valid. 

```shell
Error from server (Invalid): error when creating "k8/debeziumservers.debezium.io-v1.yml": CustomResourceDefinition.apiextensions.k8s.io "debeziumservers.debezium.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[source].properties[offset].properties[flushMs].default: Invalid value: "string":  in body must be of type integer: 
```

### Fabric8 Kubernetes Client version

6.13.4

### Steps to reproduce

Maybe adding a test in https://github.com/fabric8io/kubernetes-client/blob/ef5944094035a90942c044a513d82cbe384ddb0d/crd-generator/api-v2/src/test/java/io/fabric8/crdv2/generator/v1/JsonSchemaTest.java#L70 will be a good starting point to easily reproduce it. 

### Expected behavior

The correct default value should be used. 

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by mfvitale** [comment]
@andreaTP

**Comment by manusa** [comment]
### Additional context:

The issue is applicable for both the `@Default` annotation and the `@JsonProperty` `defaultValue`:

https://github.com/fabric8io/kubernetes-client/blob/4beec6259060fd4adffcf8c9dca90bd6101c9dee/crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java#L244


https://github.com/fabric8io/kubernetes-client/blob/4beec6259060fd4adffcf8c9dca90bd6101c9dee/crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/AbstractJsonSchema.java#L274

For CRD v1 this is only applicable to the `@Default` annotation, the `@JsonProperty` `defaultValue` config is not taken into account:

https://github.com/fabric8io/kubernetes-client/blob/1e952e068ac4160235e34f5399beea4acf5f5c1b/crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L451-L453


The issue is now visible because the Quarkus Operator SDK switched to use CRD v2 in https://github.com/quarkiverse/quarkus-operator-sdk/pull/927

:raised_hands::raised_hands::raised_hands: @metacosm has added a fix in Quarkus Operator SDK to be able to use CRD v1: https://github.com/quarkiverse/quarkus-operator-sdk/pull/1007

A release with the fix is available: https://github.com/quarkiverse/quarkus-operator-sdk/releases/tag/6.9.0

**Comment by metacosm** [comment]
I have also backported the change to 6.8.5, which should also be released today.

**Comment by e-roeling** [comment]
Would it be possible to backport this change to 6.13.x? We are currently on 6.13.4 and we can't update to 7.0.x directly.

**Comment by manusa** [comment]
> Would it be possible to backport this change to 6.13.x? We are currently on 6.13.4 and we can't update to 7.0.x directly.

HI @e-roeling, we can try to backport the changes if the branches didn't diverge too much.

**Comment by manusa** [comment]
Hi @e-roeling,
This PR requires backporting additional commits that affect the CRD-Generator v2 and that improve its functionality while breaking its 6.13 standard behavior.

It will probably be much less effort for you to upgrade to Kubernetes Client 7.
Unless you're bound to Java 8, there aren't really that many breaking changes in this release.
