### ISSUE TITLE
Unable to load HPAs at cluster version 1.6

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#730]
Running client library `kubernetes-client:2.2.13`, the call `client.extensions().horizontalPodAutoscalers().inNamespace(namespace).list()` fails due to exception 
"the server could not find the requested resource". 

Seems that the rest endpoint for HPA resources has changed to `apis/autoscaling/v1/namespaces/spinnaker/horizontalpodautoscalers`, and is no longer under the 
`api/extensions/v1beta1` endpoint.

**Comment by dennismartensson** [comment]
Hi we are also having this problem with or deployments.

**Comment by jcastillo-cb** [comment]
It turns out the the pod autoscaler is broken in 1.5.5 as well. It seems that the pod scalers that spinnaker creates use kind:replicaSet. However, kubernetes is looking for HPA that use ReplicaSet <note the CamelCase not camelCase 
So when you create a server group with autoscaler, it is not correctly attached to the RS. If you create one manually using the correct kind, then Spinnaker cannot find it. 

just file another ticket? or this ticket can take care of both?

**Comment by lwander** [comment]
^ This is unrelated to this client library, and is a separate issue within spinnaker

**Comment by mbukosky** [comment]
+1

**Comment by lihan** [comment]
+1

**Comment by Donnzh** [comment]
+1

**Comment by imosquera** [comment]
+1

**Comment by benmappen** [comment]
+1

**Comment by andrewbackes** [comment]
+1

**Comment by jrcast** [comment]
+1

**Comment by heligoogle** [comment]
+1

**Comment by shafqatevo** [comment]
+1

**Comment by lwander** [comment]
Likely using `kubectl autoscale` command described [here](https://kubernetes.io/docs/user-guide/kubectl/v1.6/#autoscale).

**Comment by moesy** [comment]
+1
