### ISSUE TITLE
Provide option to parse Templates without really parsing the underying objects using the typesafe DTO model

### ISSUE THREAD

**Issue by gskumar1010** [fabric8io/kubernetes-client#746]
Issue:  When users specify replicas as a parameter in the templates 

replicas: '${REPLICAS}'
 
 and below line is executed
 
`List<Template> tlist = sourceClient().templates().inNamespace(namespace).withLabels(labelMap).list().getItems();`
 
it fails with an error 

```
caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.lang.Integer from String "${REPLICAS}": not a valid Integer value
at [Source: N/A; line: -1, column: -1] (through reference chain: io.fabric8.openshift.api.model.TemplateList["items"]->java.util.ArrayList[0]->io.fabric8.openshift.api.model.Template["objects"]->java.util.ArrayList[0]->io.fabric8.openshift.api.model.DeploymentConfig["spec"]->io.fabric8.openshift.api.model.DeploymentConfigSpec["replicas"])

```

We are using 2.2.7 version

**Comment by jstrachan** [comment]
the fix lets you load a single template using the .processLocally() method - unfortunately we don't yet support listing all templates.

So now to handle templates with numeric expressions like this one:
https://github.com/jstrachan/kubernetes-client/blob/07d6f1fd640ae6b8eabd12ecde0e62ec1b477817/kubernetes-tests/src/test/resources/template-with-number-params.yml#L32-L32

you can use the .processLocally(map) method instead of .get() which will replace all the `${FOO}` expressions in the underlying json/yaml before parsing so that you can load the underlying typesafe kubernetes/openshift resources. You just need to make sure the map you pass into that method has all the parameter expressions inside or you'll still get a JSON parse error.

So here's an example of a code snippet creating a map of parameter values and loading the template (whch properly parsers the port integer from the map of values)
https://github.com/jstrachan/kubernetes-client/blob/81901b8eaa4062efec49eee3984b9cdaa5f875c1/kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/TemplateTest.java#L164-L168
