### ISSUE TITLE
Support for Retry to k8s.default.svc

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/kubernetes-client#798]
When using the client with Istio service mesh, the application is not able to connect to kubernetes.default.svc because of Envoy proxy (sidecar) is taking few seconds to get initialised, hence to avoid connection failures which will fade away after proxy comes up we can add some kind of retry mechanism

**Comment by wang-xiaowu** [comment]
i have the same scenario to use this func,
sometimes i can't create or delete an istio sidecar with istioclient,
i think with this fun i can retry the operation when this problem occurs

**Comment by manusa** [comment]
Retry is already built into the client. This issue is from 2017.
What version of the client are you using?
Are you sure it's the same issue, the client will automatically retry in several periods until the limit given it receives a `429` (Too Many Requests) or `5xx` (Server Error) HTTP status code:

https://github.com/fabric8io/kubernetes-client/blob/9e9e650f456aabaf5b8bf419b5f9744654e986e1/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java#L169
