### ISSUE TITLE
WatchTest sporadic failures in our release environment

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#818]
`testHttpErrorWithOutdated`
http://jenkins.cd.k8s.fabric8.io/job/fabric8-cd/job/kubernetes-client/job/master/42/console

TBH, I am not sure I get the purpose if this test, but it does seem to randomly fail.

`testHttpErrorReconnect`:
http://jenkins.cd.k8s.fabric8.io/job/fabric8-cd/job/kubernetes-client/job/master/43/console

It seems that it stuck during reconnect for some reason and it doesn't even get to the 6 reconnection attempts.

**Comment by iocanel** [comment]
@gyoetam: Can you have a look?

**Comment by gyoetam** [comment]
@iocanel: 
`testHttpErrorWithOutdated`:
The purpose of this test is to start a watch with a resource version that is already cleared from history, to check that this case is handled correctly. Expected behavior is a KubernetesClientException on watch startup and no callbacks to the listener. This is in contrast with the `testDeletedAndOutdated` case where we successfully connect, and a later time the server clears the history, resulting in an onClose callback for the watcher.
Looking at the full console log I see a NullPointerException being thrown by okio http when connecting to the mock server - at first glance this doesn't seem to be related to the actual watch code. 
Was there an update to okio / okhttp maybe that could cause this?
> 10:19:54.807 [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@2dacad1d
Jul 12, 2017 10:19:54 AM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[57247] starting to accept connections
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at okio.Okio$1.write(Okio.java:78)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:53)
	at okhttp3.internal.http1.Http1Codec.writeRequest(Http1Codec.java:175)
	at okhttp3.internal.http1.Http1Codec.writeRequestHeaders(Http1Codec.java:128)

`testHttpErrorReconnect`:
Can you reproduce the issue in a different environment? I just ran the tests on my local computer (with `mvn clean install test`, maven 3.5.0), and it works fine: after the initial onClose, I see MockWebServer$3 starting again, and the watch receives the expected 503 answer 6 times.
> 06:59:48.547 [reconnectAttempt|Executor for Watch 228585933] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@d9ff1cd
Jul 13, 2017 6:59:48 AM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[40007] received request: GET /api/v1/namespaces/test/pods?fieldSelector=metadata.name%3Dpod1&resourceVersion=1&watch=true HTTP/1.1 and responded: HTTP/1.1 503 Server Error

In the jenkins output however, it seems like the test is stuck because the mock server is not accepting connections again after the first disconnect. I currently have no idea why that is happening, I'm not familiar with the mock server internals or your build pipeline. :(
>10:45:04.083 [reconnectAttempt|Executor for Watch 1085793932] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@40b7e68c
10:48:03.076 [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Force closing the watch

**Comment by iocanel** [comment]
@gyoetam: Thanks! 

In most environments things are working great, with only exception our release box.
