### ISSUE TITLE
TemplateOperationsImpl.processLocally fails on replacing template parameters in names (and prob other fields with regex constraints

### ISSUE THREAD

**Issue by andreasschramm** [fabric8io/kubernetes-client#916]
implementation tries to build a kubernetesList from template.objects, in order to serialize the resulting list as a string, and do the replacing by String.replace afterwards.
if, however, one of the created objects has a variable in its,name, like "${PREFIX}-account", creating the Kubernetes list fails, since the default constructor of KubernetesListBuilder has validationEnabled=true, and the name (with the variable in it) does not validate.

### Stacktrace:
`javax.validation.ConstraintViolationException: Constraint Validations: metadata.name must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$" on bean: Secret(apiVersion=v1, data={}, kind=Secret, metadata=ObjectMeta(annotations={}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={application=${APPLICATION_NAME}, type=application}, name=redis-${APPLICATION_NAME}-application-secret, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), stringData={redis-password=${REDIS_PASSWORD}}, type=null, additionalProperties={})

	at io.fabric8.kubernetes.api.builder.ValidationUtils.validate(ValidationUtils.java:36)
	at io.fabric8.kubernetes.api.model.SecretBuilder.build(SecretBuilder.java:53)
	at io.fabric8.kubernetes.api.model.SecretBuilder.build(SecretBuilder.java:7)
	at io.fabric8.kubernetes.api.builder.BaseFluent.build(BaseFluent.java:20)
	at io.fabric8.kubernetes.api.model.BaseKubernetesListFluentImpl.getItems(BaseKubernetesListFluentImpl.java:558)
	at io.fabric8.kubernetes.api.model.KubernetesListBuilder.build(KubernetesListBuilder.java:48)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:182)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
`

### Suggested Solution:
 use a KubernetesListbuilder with validationEnabled=false, 

I think validation of the generated objects should be by default left to the server side. (api version, etc)

**Comment by KaiJunYan** [comment]
@andreasschramm  
cloud you tell me how to use a KubernetesListbuilder with validationEnabled=false,  thanks

**Comment by ctron** [comment]
There are two bugs here, needed to be fixed. And this only happens when you have proper javax.validation support on your classpath.

The first bug is in the farbic8 kubernetes client, in the `TemplateOperation`:

~~~java
KubernetesList list = new KubernetesListBuilder()
  .withItems(t != null && t.getObjects() != null ? t.getObjects() : Collections.<HasMetadata>emptyList())
  .build();
~~~

The builder should be initialized with `validation=false`:

~~~java
KubernetesList list = new KubernetesListBuilder(false)
  .withItems(t != null && t.getObjects() != null ? t.getObjects() : Collections.<HasMetadata>emptyList())
  .build();
~~~

However, this will only work if the client is generated with a newer version of the builder generator (https://github.com/sundrio/sundrio), otherwise the builder framework will generate the following code:

~~~java
public KubernetesList build(){
  KubernetesList buildable = new KubernetesList(fluent.getApiVersion(),fluent.getItems(),fluent.getKind(),fluent.getMetadata());
  io.fabric8.kubernetes.api.builder.ValidationUtils.validate(buildable);
  return buildable;
}
~~~

Which would mean that although the validation is disabled, the check is not done, and validation is still be triggered.

A version of 0.9.x seems to work: https://github.com/sundrio/sundrio/releases
